/**
 * 毕业设计跳蚤市场
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OrderConfirmRequest model module.
 * @module model/OrderConfirmRequest
 * @version 1.0.0
 */
class OrderConfirmRequest {
    /**
     * Constructs a new <code>OrderConfirmRequest</code>.
     * 订单确认请求
     * @alias module:model/OrderConfirmRequest
     */
    constructor() { 
        
        OrderConfirmRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OrderConfirmRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OrderConfirmRequest} obj Optional instance to populate.
     * @return {module:model/OrderConfirmRequest} The populated <code>OrderConfirmRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrderConfirmRequest();

            if (data.hasOwnProperty('orderId')) {
                obj['orderId'] = ApiClient.convertToType(data['orderId'], 'Number');
            }
            if (data.hasOwnProperty('confirmType')) {
                obj['confirmType'] = ApiClient.convertToType(data['confirmType'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OrderConfirmRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OrderConfirmRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }


}



/**
 * @member {Number} orderId
 */
OrderConfirmRequest.prototype['orderId'] = undefined;

/**
 * @member {Number} confirmType
 */
OrderConfirmRequest.prototype['confirmType'] = undefined;

/**
 * @member {String} description
 */
OrderConfirmRequest.prototype['description'] = undefined;






export default OrderConfirmRequest;

