/**
 * 毕业设计跳蚤市场
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import User from './User';

/**
 * The Order model module.
 * @module model/Order
 * @version 1.0.0
 */
class Order {
    /**
     * Constructs a new <code>Order</code>.
     * @alias module:model/Order
     */
    constructor() { 
        
        Order.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Order</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Order} obj Optional instance to populate.
     * @return {module:model/Order} The populated <code>Order</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Order();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('productId')) {
                obj['productId'] = ApiClient.convertToType(data['productId'], 'Number');
            }
            if (data.hasOwnProperty('buyer')) {
                obj['buyer'] = User.constructFromObject(data['buyer']);
            }
            if (data.hasOwnProperty('seller')) {
                obj['seller'] = User.constructFromObject(data['seller']);
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('paymentMethod')) {
                obj['paymentMethod'] = ApiClient.convertToType(data['paymentMethod'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
            if (data.hasOwnProperty('paymentProof')) {
                obj['paymentProof'] = ApiClient.convertToType(data['paymentProof'], 'String');
            }
            if (data.hasOwnProperty('buyerConfirmed')) {
                obj['buyerConfirmed'] = ApiClient.convertToType(data['buyerConfirmed'], 'Boolean');
            }
            if (data.hasOwnProperty('sellerConfirmed')) {
                obj['sellerConfirmed'] = ApiClient.convertToType(data['sellerConfirmed'], 'Boolean');
            }
            if (data.hasOwnProperty('createTime')) {
                obj['createTime'] = ApiClient.convertToType(data['createTime'], 'Date');
            }
            if (data.hasOwnProperty('finishTime')) {
                obj['finishTime'] = ApiClient.convertToType(data['finishTime'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Order</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Order</code>.
     */
    static validateJSON(data) {
        // validate the optional field `buyer`
        if (data['buyer']) { // data not null
          User.validateJSON(data['buyer']);
        }
        // validate the optional field `seller`
        if (data['seller']) { // data not null
          User.validateJSON(data['seller']);
        }
        // ensure the json data is a string
        if (data['paymentProof'] && !(typeof data['paymentProof'] === 'string' || data['paymentProof'] instanceof String)) {
            throw new Error("Expected the field `paymentProof` to be a primitive type in the JSON string but got " + data['paymentProof']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
Order.prototype['id'] = undefined;

/**
 * @member {Number} productId
 */
Order.prototype['productId'] = undefined;

/**
 * @member {module:model/User} buyer
 */
Order.prototype['buyer'] = undefined;

/**
 * @member {module:model/User} seller
 */
Order.prototype['seller'] = undefined;

/**
 * @member {Number} amount
 */
Order.prototype['amount'] = undefined;

/**
 * @member {Number} paymentMethod
 */
Order.prototype['paymentMethod'] = undefined;

/**
 * @member {Number} status
 */
Order.prototype['status'] = undefined;

/**
 * @member {String} paymentProof
 */
Order.prototype['paymentProof'] = undefined;

/**
 * @member {Boolean} buyerConfirmed
 */
Order.prototype['buyerConfirmed'] = undefined;

/**
 * @member {Boolean} sellerConfirmed
 */
Order.prototype['sellerConfirmed'] = undefined;

/**
 * @member {Date} createTime
 */
Order.prototype['createTime'] = undefined;

/**
 * @member {Date} finishTime
 */
Order.prototype['finishTime'] = undefined;






export default Order;

