/**
 * 毕业设计跳蚤市场
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OrderRequest model module.
 * @module model/OrderRequest
 * @version 1.0.0
 */
class OrderRequest {
    /**
     * Constructs a new <code>OrderRequest</code>.
     * @alias module:model/OrderRequest
     */
    constructor() { 
        
        OrderRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OrderRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OrderRequest} obj Optional instance to populate.
     * @return {module:model/OrderRequest} The populated <code>OrderRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrderRequest();

            if (data.hasOwnProperty('totalOrders')) {
                obj['totalOrders'] = ApiClient.convertToType(data['totalOrders'], 'Number');
            }
            if (data.hasOwnProperty('pendingPaymentOrders')) {
                obj['pendingPaymentOrders'] = ApiClient.convertToType(data['pendingPaymentOrders'], 'Number');
            }
            if (data.hasOwnProperty('paidOrders')) {
                obj['paidOrders'] = ApiClient.convertToType(data['paidOrders'], 'Number');
            }
            if (data.hasOwnProperty('completedOrders')) {
                obj['completedOrders'] = ApiClient.convertToType(data['completedOrders'], 'Number');
            }
            if (data.hasOwnProperty('cancelledOrders')) {
                obj['cancelledOrders'] = ApiClient.convertToType(data['cancelledOrders'], 'Number');
            }
            if (data.hasOwnProperty('totalAmount')) {
                obj['totalAmount'] = ApiClient.convertToType(data['totalAmount'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OrderRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OrderRequest</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} totalOrders
 */
OrderRequest.prototype['totalOrders'] = undefined;

/**
 * @member {Number} pendingPaymentOrders
 */
OrderRequest.prototype['pendingPaymentOrders'] = undefined;

/**
 * @member {Number} paidOrders
 */
OrderRequest.prototype['paidOrders'] = undefined;

/**
 * @member {Number} completedOrders
 */
OrderRequest.prototype['completedOrders'] = undefined;

/**
 * @member {Number} cancelledOrders
 */
OrderRequest.prototype['cancelledOrders'] = undefined;

/**
 * @member {Number} totalAmount
 */
OrderRequest.prototype['totalAmount'] = undefined;






export default OrderRequest;

