/**
 * 毕业设计跳蚤市场
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PageRequest model module.
 * @module model/PageRequest
 * @version 1.0.0
 */
class PageRequest {
    /**
     * Constructs a new <code>PageRequest</code>.
     * @alias module:model/PageRequest
     */
    constructor() { 
        
        PageRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PageRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PageRequest} obj Optional instance to populate.
     * @return {module:model/PageRequest} The populated <code>PageRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PageRequest();

            if (data.hasOwnProperty('current')) {
                obj['current'] = ApiClient.convertToType(data['current'], 'Number');
            }
            if (data.hasOwnProperty('pageSize')) {
                obj['pageSize'] = ApiClient.convertToType(data['pageSize'], 'Number');
            }
            if (data.hasOwnProperty('sortField')) {
                obj['sortField'] = ApiClient.convertToType(data['sortField'], 'String');
            }
            if (data.hasOwnProperty('sortOrder')) {
                obj['sortOrder'] = ApiClient.convertToType(data['sortOrder'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PageRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PageRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['sortField'] && !(typeof data['sortField'] === 'string' || data['sortField'] instanceof String)) {
            throw new Error("Expected the field `sortField` to be a primitive type in the JSON string but got " + data['sortField']);
        }
        // ensure the json data is a string
        if (data['sortOrder'] && !(typeof data['sortOrder'] === 'string' || data['sortOrder'] instanceof String)) {
            throw new Error("Expected the field `sortOrder` to be a primitive type in the JSON string but got " + data['sortOrder']);
        }

        return true;
    }


}



/**
 * @member {Number} current
 */
PageRequest.prototype['current'] = undefined;

/**
 * @member {Number} pageSize
 */
PageRequest.prototype['pageSize'] = undefined;

/**
 * @member {String} sortField
 */
PageRequest.prototype['sortField'] = undefined;

/**
 * @member {String} sortOrder
 */
PageRequest.prototype['sortOrder'] = undefined;






export default PageRequest;

