/**
 * 毕业设计跳蚤市场
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OrderItem from './OrderItem';
import Review from './Review';

/**
 * The PageReview model module.
 * @module model/PageReview
 * @version 1.0.0
 */
class PageReview {
    /**
     * Constructs a new <code>PageReview</code>.
     * @alias module:model/PageReview
     */
    constructor() { 
        
        PageReview.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PageReview</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PageReview} obj Optional instance to populate.
     * @return {module:model/PageReview} The populated <code>PageReview</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PageReview();

            if (data.hasOwnProperty('records')) {
                obj['records'] = ApiClient.convertToType(data['records'], [Review]);
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('current')) {
                obj['current'] = ApiClient.convertToType(data['current'], 'Number');
            }
            if (data.hasOwnProperty('orders')) {
                obj['orders'] = ApiClient.convertToType(data['orders'], [OrderItem]);
            }
            if (data.hasOwnProperty('optimizeCountSql')) {
                obj['optimizeCountSql'] = PageReview.constructFromObject(data['optimizeCountSql']);
            }
            if (data.hasOwnProperty('searchCount')) {
                obj['searchCount'] = PageReview.constructFromObject(data['searchCount']);
            }
            if (data.hasOwnProperty('optimizeJoinOfCountSql')) {
                obj['optimizeJoinOfCountSql'] = ApiClient.convertToType(data['optimizeJoinOfCountSql'], 'Boolean');
            }
            if (data.hasOwnProperty('maxLimit')) {
                obj['maxLimit'] = ApiClient.convertToType(data['maxLimit'], 'Number');
            }
            if (data.hasOwnProperty('countId')) {
                obj['countId'] = ApiClient.convertToType(data['countId'], 'String');
            }
            if (data.hasOwnProperty('pages')) {
                obj['pages'] = ApiClient.convertToType(data['pages'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PageReview</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PageReview</code>.
     */
    static validateJSON(data) {
        if (data['records']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['records'])) {
                throw new Error("Expected the field `records` to be an array in the JSON data but got " + data['records']);
            }
            // validate the optional field `records` (array)
            for (const item of data['records']) {
                Review.validateJSON(item);
            };
        }
        if (data['orders']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['orders'])) {
                throw new Error("Expected the field `orders` to be an array in the JSON data but got " + data['orders']);
            }
            // validate the optional field `orders` (array)
            for (const item of data['orders']) {
                OrderItem.validateJSON(item);
            };
        }
        // validate the optional field `optimizeCountSql`
        if (data['optimizeCountSql']) { // data not null
          PageReview.validateJSON(data['optimizeCountSql']);
        }
        // validate the optional field `searchCount`
        if (data['searchCount']) { // data not null
          PageReview.validateJSON(data['searchCount']);
        }
        // ensure the json data is a string
        if (data['countId'] && !(typeof data['countId'] === 'string' || data['countId'] instanceof String)) {
            throw new Error("Expected the field `countId` to be a primitive type in the JSON string but got " + data['countId']);
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/Review>} records
 */
PageReview.prototype['records'] = undefined;

/**
 * @member {Number} total
 */
PageReview.prototype['total'] = undefined;

/**
 * @member {Number} size
 */
PageReview.prototype['size'] = undefined;

/**
 * @member {Number} current
 */
PageReview.prototype['current'] = undefined;

/**
 * @member {Array.<module:model/OrderItem>} orders
 */
PageReview.prototype['orders'] = undefined;

/**
 * @member {module:model/PageReview} optimizeCountSql
 */
PageReview.prototype['optimizeCountSql'] = undefined;

/**
 * @member {module:model/PageReview} searchCount
 */
PageReview.prototype['searchCount'] = undefined;

/**
 * @member {Boolean} optimizeJoinOfCountSql
 */
PageReview.prototype['optimizeJoinOfCountSql'] = undefined;

/**
 * @member {Number} maxLimit
 */
PageReview.prototype['maxLimit'] = undefined;

/**
 * @member {String} countId
 */
PageReview.prototype['countId'] = undefined;

/**
 * @member {Number} pages
 */
PageReview.prototype['pages'] = undefined;






export default PageReview;

