/**
 * 毕业设计跳蚤市场
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProductRankingItem model module.
 * @module model/ProductRankingItem
 * @version 1.0.0
 */
class ProductRankingItem {
    /**
     * Constructs a new <code>ProductRankingItem</code>.
     * @alias module:model/ProductRankingItem
     */
    constructor() { 
        
        ProductRankingItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductRankingItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductRankingItem} obj Optional instance to populate.
     * @return {module:model/ProductRankingItem} The populated <code>ProductRankingItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductRankingItem();

            if (data.hasOwnProperty('productId')) {
                obj['productId'] = ApiClient.convertToType(data['productId'], 'Number');
            }
            if (data.hasOwnProperty('productName')) {
                obj['productName'] = ApiClient.convertToType(data['productName'], 'String');
            }
            if (data.hasOwnProperty('tradeCount')) {
                obj['tradeCount'] = ApiClient.convertToType(data['tradeCount'], 'Number');
            }
            if (data.hasOwnProperty('tradeAmount')) {
                obj['tradeAmount'] = ApiClient.convertToType(data['tradeAmount'], 'Number');
            }
            if (data.hasOwnProperty('imageUrl')) {
                obj['imageUrl'] = ApiClient.convertToType(data['imageUrl'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProductRankingItem</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProductRankingItem</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['productName'] && !(typeof data['productName'] === 'string' || data['productName'] instanceof String)) {
            throw new Error("Expected the field `productName` to be a primitive type in the JSON string but got " + data['productName']);
        }
        // ensure the json data is a string
        if (data['imageUrl'] && !(typeof data['imageUrl'] === 'string' || data['imageUrl'] instanceof String)) {
            throw new Error("Expected the field `imageUrl` to be a primitive type in the JSON string but got " + data['imageUrl']);
        }

        return true;
    }


}



/**
 * @member {Number} productId
 */
ProductRankingItem.prototype['productId'] = undefined;

/**
 * @member {String} productName
 */
ProductRankingItem.prototype['productName'] = undefined;

/**
 * @member {Number} tradeCount
 */
ProductRankingItem.prototype['tradeCount'] = undefined;

/**
 * @member {Number} tradeAmount
 */
ProductRankingItem.prototype['tradeAmount'] = undefined;

/**
 * @member {String} imageUrl
 */
ProductRankingItem.prototype['imageUrl'] = undefined;






export default ProductRankingItem;

