/**
 * 毕业设计跳蚤市场
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ReviewRequest model module.
 * @module model/ReviewRequest
 * @version 1.0.0
 */
class ReviewRequest {
    /**
     * Constructs a new <code>ReviewRequest</code>.
     * @alias module:model/ReviewRequest
     */
    constructor() { 
        
        ReviewRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ReviewRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ReviewRequest} obj Optional instance to populate.
     * @return {module:model/ReviewRequest} The populated <code>ReviewRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReviewRequest();

            if (data.hasOwnProperty('totalReviews')) {
                obj['totalReviews'] = ApiClient.convertToType(data['totalReviews'], 'Number');
            }
            if (data.hasOwnProperty('averageRating')) {
                obj['averageRating'] = ApiClient.convertToType(data['averageRating'], 'Number');
            }
            if (data.hasOwnProperty('fiveStarCount')) {
                obj['fiveStarCount'] = ApiClient.convertToType(data['fiveStarCount'], 'Number');
            }
            if (data.hasOwnProperty('fourStarCount')) {
                obj['fourStarCount'] = ApiClient.convertToType(data['fourStarCount'], 'Number');
            }
            if (data.hasOwnProperty('threeStarCount')) {
                obj['threeStarCount'] = ApiClient.convertToType(data['threeStarCount'], 'Number');
            }
            if (data.hasOwnProperty('twoStarCount')) {
                obj['twoStarCount'] = ApiClient.convertToType(data['twoStarCount'], 'Number');
            }
            if (data.hasOwnProperty('oneStarCount')) {
                obj['oneStarCount'] = ApiClient.convertToType(data['oneStarCount'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ReviewRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ReviewRequest</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} totalReviews
 */
ReviewRequest.prototype['totalReviews'] = undefined;

/**
 * @member {Number} averageRating
 */
ReviewRequest.prototype['averageRating'] = undefined;

/**
 * @member {Number} fiveStarCount
 */
ReviewRequest.prototype['fiveStarCount'] = undefined;

/**
 * @member {Number} fourStarCount
 */
ReviewRequest.prototype['fourStarCount'] = undefined;

/**
 * @member {Number} threeStarCount
 */
ReviewRequest.prototype['threeStarCount'] = undefined;

/**
 * @member {Number} twoStarCount
 */
ReviewRequest.prototype['twoStarCount'] = undefined;

/**
 * @member {Number} oneStarCount
 */
ReviewRequest.prototype['oneStarCount'] = undefined;






export default ReviewRequest;

