/**
 * 毕业设计跳蚤市场
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProductRankingItem from './ProductRankingItem';
import UserRankingItem from './UserRankingItem';

/**
 * The StatisticsResponse model module.
 * @module model/StatisticsResponse
 * @version 1.0.0
 */
class StatisticsResponse {
    /**
     * Constructs a new <code>StatisticsResponse</code>.
     * @alias module:model/StatisticsResponse
     */
    constructor() { 
        
        StatisticsResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StatisticsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StatisticsResponse} obj Optional instance to populate.
     * @return {module:model/StatisticsResponse} The populated <code>StatisticsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StatisticsResponse();

            if (data.hasOwnProperty('statisticsType')) {
                obj['statisticsType'] = ApiClient.convertToType(data['statisticsType'], 'String');
            }
            if (data.hasOwnProperty('statisticsTime')) {
                obj['statisticsTime'] = ApiClient.convertToType(data['statisticsTime'], 'Date');
            }
            if (data.hasOwnProperty('totalTradeAmount')) {
                obj['totalTradeAmount'] = ApiClient.convertToType(data['totalTradeAmount'], 'Number');
            }
            if (data.hasOwnProperty('totalTradeCount')) {
                obj['totalTradeCount'] = ApiClient.convertToType(data['totalTradeCount'], 'Number');
            }
            if (data.hasOwnProperty('monthlyProductRanking')) {
                obj['monthlyProductRanking'] = ApiClient.convertToType(data['monthlyProductRanking'], [ProductRankingItem]);
            }
            if (data.hasOwnProperty('activeUserRanking')) {
                obj['activeUserRanking'] = ApiClient.convertToType(data['activeUserRanking'], [UserRankingItem]);
            }
            if (data.hasOwnProperty('highDemandRanking')) {
                obj['highDemandRanking'] = ApiClient.convertToType(data['highDemandRanking'], [ProductRankingItem]);
            }
            if (data.hasOwnProperty('highInventoryRanking')) {
                obj['highInventoryRanking'] = ApiClient.convertToType(data['highInventoryRanking'], [ProductRankingItem]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StatisticsResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StatisticsResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['statisticsType'] && !(typeof data['statisticsType'] === 'string' || data['statisticsType'] instanceof String)) {
            throw new Error("Expected the field `statisticsType` to be a primitive type in the JSON string but got " + data['statisticsType']);
        }
        if (data['monthlyProductRanking']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['monthlyProductRanking'])) {
                throw new Error("Expected the field `monthlyProductRanking` to be an array in the JSON data but got " + data['monthlyProductRanking']);
            }
            // validate the optional field `monthlyProductRanking` (array)
            for (const item of data['monthlyProductRanking']) {
                ProductRankingItem.validateJSON(item);
            };
        }
        if (data['activeUserRanking']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['activeUserRanking'])) {
                throw new Error("Expected the field `activeUserRanking` to be an array in the JSON data but got " + data['activeUserRanking']);
            }
            // validate the optional field `activeUserRanking` (array)
            for (const item of data['activeUserRanking']) {
                UserRankingItem.validateJSON(item);
            };
        }
        if (data['highDemandRanking']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['highDemandRanking'])) {
                throw new Error("Expected the field `highDemandRanking` to be an array in the JSON data but got " + data['highDemandRanking']);
            }
            // validate the optional field `highDemandRanking` (array)
            for (const item of data['highDemandRanking']) {
                ProductRankingItem.validateJSON(item);
            };
        }
        if (data['highInventoryRanking']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['highInventoryRanking'])) {
                throw new Error("Expected the field `highInventoryRanking` to be an array in the JSON data but got " + data['highInventoryRanking']);
            }
            // validate the optional field `highInventoryRanking` (array)
            for (const item of data['highInventoryRanking']) {
                ProductRankingItem.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {String} statisticsType
 */
StatisticsResponse.prototype['statisticsType'] = undefined;

/**
 * @member {Date} statisticsTime
 */
StatisticsResponse.prototype['statisticsTime'] = undefined;

/**
 * @member {Number} totalTradeAmount
 */
StatisticsResponse.prototype['totalTradeAmount'] = undefined;

/**
 * @member {Number} totalTradeCount
 */
StatisticsResponse.prototype['totalTradeCount'] = undefined;

/**
 * @member {Array.<module:model/ProductRankingItem>} monthlyProductRanking
 */
StatisticsResponse.prototype['monthlyProductRanking'] = undefined;

/**
 * @member {Array.<module:model/UserRankingItem>} activeUserRanking
 */
StatisticsResponse.prototype['activeUserRanking'] = undefined;

/**
 * @member {Array.<module:model/ProductRankingItem>} highDemandRanking
 */
StatisticsResponse.prototype['highDemandRanking'] = undefined;

/**
 * @member {Array.<module:model/ProductRankingItem>} highInventoryRanking
 */
StatisticsResponse.prototype['highInventoryRanking'] = undefined;






export default StatisticsResponse;

