/**
 * 毕业设计跳蚤市场
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TradeRecord model module.
 * @module model/TradeRecord
 * @version 1.0.0
 */
class TradeRecord {
    /**
     * Constructs a new <code>TradeRecord</code>.
     * @alias module:model/TradeRecord
     */
    constructor() { 
        
        TradeRecord.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TradeRecord</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TradeRecord} obj Optional instance to populate.
     * @return {module:model/TradeRecord} The populated <code>TradeRecord</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TradeRecord();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('orderId')) {
                obj['orderId'] = ApiClient.convertToType(data['orderId'], 'Number');
            }
            if (data.hasOwnProperty('productId')) {
                obj['productId'] = ApiClient.convertToType(data['productId'], 'Number');
            }
            if (data.hasOwnProperty('productName')) {
                obj['productName'] = ApiClient.convertToType(data['productName'], 'String');
            }
            if (data.hasOwnProperty('buyerId')) {
                obj['buyerId'] = ApiClient.convertToType(data['buyerId'], 'Number');
            }
            if (data.hasOwnProperty('buyerName')) {
                obj['buyerName'] = ApiClient.convertToType(data['buyerName'], 'String');
            }
            if (data.hasOwnProperty('sellerId')) {
                obj['sellerId'] = ApiClient.convertToType(data['sellerId'], 'Number');
            }
            if (data.hasOwnProperty('sellerName')) {
                obj['sellerName'] = ApiClient.convertToType(data['sellerName'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('paymentMethod')) {
                obj['paymentMethod'] = ApiClient.convertToType(data['paymentMethod'], 'Number');
            }
            if (data.hasOwnProperty('paymentMethodDesc')) {
                obj['paymentMethodDesc'] = ApiClient.convertToType(data['paymentMethodDesc'], 'String');
            }
            if (data.hasOwnProperty('tradeTime')) {
                obj['tradeTime'] = ApiClient.convertToType(data['tradeTime'], 'Date');
            }
            if (data.hasOwnProperty('tradeStatus')) {
                obj['tradeStatus'] = ApiClient.convertToType(data['tradeStatus'], 'Number');
            }
            if (data.hasOwnProperty('remark')) {
                obj['remark'] = ApiClient.convertToType(data['remark'], 'String');
            }
            if (data.hasOwnProperty('reviewId')) {
                obj['reviewId'] = ApiClient.convertToType(data['reviewId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TradeRecord</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TradeRecord</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['productName'] && !(typeof data['productName'] === 'string' || data['productName'] instanceof String)) {
            throw new Error("Expected the field `productName` to be a primitive type in the JSON string but got " + data['productName']);
        }
        // ensure the json data is a string
        if (data['buyerName'] && !(typeof data['buyerName'] === 'string' || data['buyerName'] instanceof String)) {
            throw new Error("Expected the field `buyerName` to be a primitive type in the JSON string but got " + data['buyerName']);
        }
        // ensure the json data is a string
        if (data['sellerName'] && !(typeof data['sellerName'] === 'string' || data['sellerName'] instanceof String)) {
            throw new Error("Expected the field `sellerName` to be a primitive type in the JSON string but got " + data['sellerName']);
        }
        // ensure the json data is a string
        if (data['paymentMethodDesc'] && !(typeof data['paymentMethodDesc'] === 'string' || data['paymentMethodDesc'] instanceof String)) {
            throw new Error("Expected the field `paymentMethodDesc` to be a primitive type in the JSON string but got " + data['paymentMethodDesc']);
        }
        // ensure the json data is a string
        if (data['remark'] && !(typeof data['remark'] === 'string' || data['remark'] instanceof String)) {
            throw new Error("Expected the field `remark` to be a primitive type in the JSON string but got " + data['remark']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
TradeRecord.prototype['id'] = undefined;

/**
 * @member {Number} orderId
 */
TradeRecord.prototype['orderId'] = undefined;

/**
 * @member {Number} productId
 */
TradeRecord.prototype['productId'] = undefined;

/**
 * @member {String} productName
 */
TradeRecord.prototype['productName'] = undefined;

/**
 * @member {Number} buyerId
 */
TradeRecord.prototype['buyerId'] = undefined;

/**
 * @member {String} buyerName
 */
TradeRecord.prototype['buyerName'] = undefined;

/**
 * @member {Number} sellerId
 */
TradeRecord.prototype['sellerId'] = undefined;

/**
 * @member {String} sellerName
 */
TradeRecord.prototype['sellerName'] = undefined;

/**
 * @member {Number} amount
 */
TradeRecord.prototype['amount'] = undefined;

/**
 * @member {Number} paymentMethod
 */
TradeRecord.prototype['paymentMethod'] = undefined;

/**
 * @member {String} paymentMethodDesc
 */
TradeRecord.prototype['paymentMethodDesc'] = undefined;

/**
 * @member {Date} tradeTime
 */
TradeRecord.prototype['tradeTime'] = undefined;

/**
 * @member {Number} tradeStatus
 */
TradeRecord.prototype['tradeStatus'] = undefined;

/**
 * @member {String} remark
 */
TradeRecord.prototype['remark'] = undefined;

/**
 * @member {Number} reviewId
 */
TradeRecord.prototype['reviewId'] = undefined;






export default TradeRecord;

