/**
 * 毕业设计跳蚤市场
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserRankingItem model module.
 * @module model/UserRankingItem
 * @version 1.0.0
 */
class UserRankingItem {
    /**
     * Constructs a new <code>UserRankingItem</code>.
     * @alias module:model/UserRankingItem
     */
    constructor() { 
        
        UserRankingItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserRankingItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserRankingItem} obj Optional instance to populate.
     * @return {module:model/UserRankingItem} The populated <code>UserRankingItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserRankingItem();

            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'Number');
            }
            if (data.hasOwnProperty('userName')) {
                obj['userName'] = ApiClient.convertToType(data['userName'], 'String');
            }
            if (data.hasOwnProperty('tradeCount')) {
                obj['tradeCount'] = ApiClient.convertToType(data['tradeCount'], 'Number');
            }
            if (data.hasOwnProperty('tradeAmount')) {
                obj['tradeAmount'] = ApiClient.convertToType(data['tradeAmount'], 'Number');
            }
            if (data.hasOwnProperty('avatar')) {
                obj['avatar'] = ApiClient.convertToType(data['avatar'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserRankingItem</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserRankingItem</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['userName'] && !(typeof data['userName'] === 'string' || data['userName'] instanceof String)) {
            throw new Error("Expected the field `userName` to be a primitive type in the JSON string but got " + data['userName']);
        }
        // ensure the json data is a string
        if (data['avatar'] && !(typeof data['avatar'] === 'string' || data['avatar'] instanceof String)) {
            throw new Error("Expected the field `avatar` to be a primitive type in the JSON string but got " + data['avatar']);
        }

        return true;
    }


}



/**
 * @member {Number} userId
 */
UserRankingItem.prototype['userId'] = undefined;

/**
 * @member {String} userName
 */
UserRankingItem.prototype['userName'] = undefined;

/**
 * @member {Number} tradeCount
 */
UserRankingItem.prototype['tradeCount'] = undefined;

/**
 * @member {Number} tradeAmount
 */
UserRankingItem.prototype['tradeAmount'] = undefined;

/**
 * @member {String} avatar
 */
UserRankingItem.prototype['avatar'] = undefined;






export default UserRankingItem;

