/**
 * 毕业设计跳蚤市场
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserAuditRequest model module.
 * @module model/UserAuditRequest
 * @version 1.0.0
 */
class UserAuditRequest {
    /**
     * Constructs a new <code>UserAuditRequest</code>.
     * 用户审核请求
     * @alias module:model/UserAuditRequest
     */
    constructor() { 
        
        UserAuditRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserAuditRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserAuditRequest} obj Optional instance to populate.
     * @return {module:model/UserAuditRequest} The populated <code>UserAuditRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserAuditRequest();

            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'Number');
            }
            if (data.hasOwnProperty('auditStatus')) {
                obj['auditStatus'] = ApiClient.convertToType(data['auditStatus'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserAuditRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserAuditRequest</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} userId
 */
UserAuditRequest.prototype['userId'] = undefined;

/**
 * @member {Number} auditStatus
 */
UserAuditRequest.prototype['auditStatus'] = undefined;






export default UserAuditRequest;

