/**
 * 毕业设计跳蚤市场
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserVo model module.
 * @module model/UserVo
 * @version 1.0.0
 */
class UserVo {
    /**
     * Constructs a new <code>UserVo</code>.
     * @alias module:model/UserVo
     */
    constructor() { 
        
        UserVo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserVo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserVo} obj Optional instance to populate.
     * @return {module:model/UserVo} The populated <code>UserVo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserVo();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('userName')) {
                obj['userName'] = ApiClient.convertToType(data['userName'], 'String');
            }
            if (data.hasOwnProperty('userAvatar')) {
                obj['userAvatar'] = ApiClient.convertToType(data['userAvatar'], 'String');
            }
            if (data.hasOwnProperty('userRole')) {
                obj['userRole'] = ApiClient.convertToType(data['userRole'], 'String');
            }
            if (data.hasOwnProperty('point')) {
                obj['point'] = ApiClient.convertToType(data['point'], 'Number');
            }
            if (data.hasOwnProperty('registerTime')) {
                obj['registerTime'] = ApiClient.convertToType(data['registerTime'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserVo</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserVo</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['userName'] && !(typeof data['userName'] === 'string' || data['userName'] instanceof String)) {
            throw new Error("Expected the field `userName` to be a primitive type in the JSON string but got " + data['userName']);
        }
        // ensure the json data is a string
        if (data['userAvatar'] && !(typeof data['userAvatar'] === 'string' || data['userAvatar'] instanceof String)) {
            throw new Error("Expected the field `userAvatar` to be a primitive type in the JSON string but got " + data['userAvatar']);
        }
        // ensure the json data is a string
        if (data['userRole'] && !(typeof data['userRole'] === 'string' || data['userRole'] instanceof String)) {
            throw new Error("Expected the field `userRole` to be a primitive type in the JSON string but got " + data['userRole']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
UserVo.prototype['id'] = undefined;

/**
 * @member {String} userName
 */
UserVo.prototype['userName'] = undefined;

/**
 * @member {String} userAvatar
 */
UserVo.prototype['userAvatar'] = undefined;

/**
 * @member {String} userRole
 */
UserVo.prototype['userRole'] = undefined;

/**
 * @member {Number} point
 */
UserVo.prototype['point'] = undefined;

/**
 * @member {Date} registerTime
 */
UserVo.prototype['registerTime'] = undefined;






export default UserVo;

