/**
 * 毕业设计跳蚤市场
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The User model module.
 * @module model/User
 * @version 1.0.0
 */
class User {
    /**
     * Constructs a new <code>User</code>.
     * @alias module:model/User
     */
    constructor() { 
        
        User.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>User</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/User} obj Optional instance to populate.
     * @return {module:model/User} The populated <code>User</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new User();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('userAccount')) {
                obj['userAccount'] = ApiClient.convertToType(data['userAccount'], 'String');
            }
            if (data.hasOwnProperty('userPassword')) {
                obj['userPassword'] = ApiClient.convertToType(data['userPassword'], 'String');
            }
            if (data.hasOwnProperty('userName')) {
                obj['userName'] = ApiClient.convertToType(data['userName'], 'String');
            }
            if (data.hasOwnProperty('userAvatar')) {
                obj['userAvatar'] = ApiClient.convertToType(data['userAvatar'], 'String');
            }
            if (data.hasOwnProperty('userRole')) {
                obj['userRole'] = ApiClient.convertToType(data['userRole'], 'String');
            }
            if (data.hasOwnProperty('userStatus')) {
                obj['userStatus'] = ApiClient.convertToType(data['userStatus'], 'Number');
            }
            if (data.hasOwnProperty('userPhone')) {
                obj['userPhone'] = ApiClient.convertToType(data['userPhone'], 'String');
            }
            if (data.hasOwnProperty('point')) {
                obj['point'] = ApiClient.convertToType(data['point'], 'Number');
            }
            if (data.hasOwnProperty('auditTime')) {
                obj['auditTime'] = ApiClient.convertToType(data['auditTime'], 'Date');
            }
            if (data.hasOwnProperty('createTime')) {
                obj['createTime'] = ApiClient.convertToType(data['createTime'], 'Date');
            }
            if (data.hasOwnProperty('updateTime')) {
                obj['updateTime'] = ApiClient.convertToType(data['updateTime'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>User</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>User</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['userAccount'] && !(typeof data['userAccount'] === 'string' || data['userAccount'] instanceof String)) {
            throw new Error("Expected the field `userAccount` to be a primitive type in the JSON string but got " + data['userAccount']);
        }
        // ensure the json data is a string
        if (data['userPassword'] && !(typeof data['userPassword'] === 'string' || data['userPassword'] instanceof String)) {
            throw new Error("Expected the field `userPassword` to be a primitive type in the JSON string but got " + data['userPassword']);
        }
        // ensure the json data is a string
        if (data['userName'] && !(typeof data['userName'] === 'string' || data['userName'] instanceof String)) {
            throw new Error("Expected the field `userName` to be a primitive type in the JSON string but got " + data['userName']);
        }
        // ensure the json data is a string
        if (data['userAvatar'] && !(typeof data['userAvatar'] === 'string' || data['userAvatar'] instanceof String)) {
            throw new Error("Expected the field `userAvatar` to be a primitive type in the JSON string but got " + data['userAvatar']);
        }
        // ensure the json data is a string
        if (data['userRole'] && !(typeof data['userRole'] === 'string' || data['userRole'] instanceof String)) {
            throw new Error("Expected the field `userRole` to be a primitive type in the JSON string but got " + data['userRole']);
        }
        // ensure the json data is a string
        if (data['userPhone'] && !(typeof data['userPhone'] === 'string' || data['userPhone'] instanceof String)) {
            throw new Error("Expected the field `userPhone` to be a primitive type in the JSON string but got " + data['userPhone']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
User.prototype['id'] = undefined;

/**
 * @member {String} userAccount
 */
User.prototype['userAccount'] = undefined;

/**
 * @member {String} userPassword
 */
User.prototype['userPassword'] = undefined;

/**
 * @member {String} userName
 */
User.prototype['userName'] = undefined;

/**
 * @member {String} userAvatar
 */
User.prototype['userAvatar'] = undefined;

/**
 * @member {String} userRole
 */
User.prototype['userRole'] = undefined;

/**
 * @member {Number} userStatus
 */
User.prototype['userStatus'] = undefined;

/**
 * @member {String} userPhone
 */
User.prototype['userPhone'] = undefined;

/**
 * @member {Number} point
 */
User.prototype['point'] = undefined;

/**
 * @member {Date} auditTime
 */
User.prototype['auditTime'] = undefined;

/**
 * @member {Date} createTime
 */
User.prototype['createTime'] = undefined;

/**
 * @member {Date} updateTime
 */
User.prototype['updateTime'] = undefined;






export default User;

