/**
 * 毕业设计跳蚤市场
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserQueryRequest model module.
 * @module model/UserQueryRequest
 * @version 1.0.0
 */
class UserQueryRequest {
    /**
     * Constructs a new <code>UserQueryRequest</code>.
     * 用户查询条件
     * @alias module:model/UserQueryRequest
     */
    constructor() { 
        
        UserQueryRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserQueryRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserQueryRequest} obj Optional instance to populate.
     * @return {module:model/UserQueryRequest} The populated <code>UserQueryRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserQueryRequest();

            if (data.hasOwnProperty('current')) {
                obj['current'] = ApiClient.convertToType(data['current'], 'Number');
            }
            if (data.hasOwnProperty('pageSize')) {
                obj['pageSize'] = ApiClient.convertToType(data['pageSize'], 'Number');
            }
            if (data.hasOwnProperty('sortField')) {
                obj['sortField'] = ApiClient.convertToType(data['sortField'], 'String');
            }
            if (data.hasOwnProperty('sortOrder')) {
                obj['sortOrder'] = ApiClient.convertToType(data['sortOrder'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('userName')) {
                obj['userName'] = ApiClient.convertToType(data['userName'], 'String');
            }
            if (data.hasOwnProperty('point')) {
                obj['point'] = ApiClient.convertToType(data['point'], 'Number');
            }
            if (data.hasOwnProperty('userRole')) {
                obj['userRole'] = ApiClient.convertToType(data['userRole'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserQueryRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserQueryRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['sortField'] && !(typeof data['sortField'] === 'string' || data['sortField'] instanceof String)) {
            throw new Error("Expected the field `sortField` to be a primitive type in the JSON string but got " + data['sortField']);
        }
        // ensure the json data is a string
        if (data['sortOrder'] && !(typeof data['sortOrder'] === 'string' || data['sortOrder'] instanceof String)) {
            throw new Error("Expected the field `sortOrder` to be a primitive type in the JSON string but got " + data['sortOrder']);
        }
        // ensure the json data is a string
        if (data['userName'] && !(typeof data['userName'] === 'string' || data['userName'] instanceof String)) {
            throw new Error("Expected the field `userName` to be a primitive type in the JSON string but got " + data['userName']);
        }
        // ensure the json data is a string
        if (data['userRole'] && !(typeof data['userRole'] === 'string' || data['userRole'] instanceof String)) {
            throw new Error("Expected the field `userRole` to be a primitive type in the JSON string but got " + data['userRole']);
        }

        return true;
    }


}



/**
 * @member {Number} current
 */
UserQueryRequest.prototype['current'] = undefined;

/**
 * @member {Number} pageSize
 */
UserQueryRequest.prototype['pageSize'] = undefined;

/**
 * @member {String} sortField
 */
UserQueryRequest.prototype['sortField'] = undefined;

/**
 * @member {String} sortOrder
 */
UserQueryRequest.prototype['sortOrder'] = undefined;

/**
 * @member {Number} id
 */
UserQueryRequest.prototype['id'] = undefined;

/**
 * @member {String} userName
 */
UserQueryRequest.prototype['userName'] = undefined;

/**
 * @member {Number} point
 */
UserQueryRequest.prototype['point'] = undefined;

/**
 * @member {String} userRole
 */
UserQueryRequest.prototype['userRole'] = undefined;






export default UserQueryRequest;

