/**
 * 毕业设计跳蚤市场
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserUpdateMyRequest model module.
 * @module model/UserUpdateMyRequest
 * @version 1.0.0
 */
class UserUpdateMyRequest {
    /**
     * Constructs a new <code>UserUpdateMyRequest</code>.
     * 个人信息更新请求
     * @alias module:model/UserUpdateMyRequest
     */
    constructor() { 
        
        UserUpdateMyRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserUpdateMyRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserUpdateMyRequest} obj Optional instance to populate.
     * @return {module:model/UserUpdateMyRequest} The populated <code>UserUpdateMyRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserUpdateMyRequest();

            if (data.hasOwnProperty('userName')) {
                obj['userName'] = ApiClient.convertToType(data['userName'], 'String');
            }
            if (data.hasOwnProperty('userAvatar')) {
                obj['userAvatar'] = ApiClient.convertToType(data['userAvatar'], 'String');
            }
            if (data.hasOwnProperty('userProfile')) {
                obj['userProfile'] = ApiClient.convertToType(data['userProfile'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserUpdateMyRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserUpdateMyRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['userName'] && !(typeof data['userName'] === 'string' || data['userName'] instanceof String)) {
            throw new Error("Expected the field `userName` to be a primitive type in the JSON string but got " + data['userName']);
        }
        // ensure the json data is a string
        if (data['userAvatar'] && !(typeof data['userAvatar'] === 'string' || data['userAvatar'] instanceof String)) {
            throw new Error("Expected the field `userAvatar` to be a primitive type in the JSON string but got " + data['userAvatar']);
        }
        // ensure the json data is a string
        if (data['userProfile'] && !(typeof data['userProfile'] === 'string' || data['userProfile'] instanceof String)) {
            throw new Error("Expected the field `userProfile` to be a primitive type in the JSON string but got " + data['userProfile']);
        }

        return true;
    }


}



/**
 * @member {String} userName
 */
UserUpdateMyRequest.prototype['userName'] = undefined;

/**
 * @member {String} userAvatar
 */
UserUpdateMyRequest.prototype['userAvatar'] = undefined;

/**
 * @member {String} userProfile
 */
UserUpdateMyRequest.prototype['userProfile'] = undefined;






export default UserUpdateMyRequest;

