/**
 * 毕业设计跳蚤市场
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserLoginRequest model module.
 * @module model/UserLoginRequest
 * @version 1.0.0
 */
class UserLoginRequest {
    /**
     * Constructs a new <code>UserLoginRequest</code>.
     * 用户登录信息
     * @alias module:model/UserLoginRequest
     */
    constructor() { 
        
        UserLoginRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserLoginRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserLoginRequest} obj Optional instance to populate.
     * @return {module:model/UserLoginRequest} The populated <code>UserLoginRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserLoginRequest();

            if (data.hasOwnProperty('userAccount')) {
                obj['userAccount'] = ApiClient.convertToType(data['userAccount'], 'String');
            }
            if (data.hasOwnProperty('userPassword')) {
                obj['userPassword'] = ApiClient.convertToType(data['userPassword'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserLoginRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserLoginRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['userAccount'] && !(typeof data['userAccount'] === 'string' || data['userAccount'] instanceof String)) {
            throw new Error("Expected the field `userAccount` to be a primitive type in the JSON string but got " + data['userAccount']);
        }
        // ensure the json data is a string
        if (data['userPassword'] && !(typeof data['userPassword'] === 'string' || data['userPassword'] instanceof String)) {
            throw new Error("Expected the field `userPassword` to be a primitive type in the JSON string but got " + data['userPassword']);
        }

        return true;
    }


}



/**
 * @member {String} userAccount
 */
UserLoginRequest.prototype['userAccount'] = undefined;

/**
 * @member {String} userPassword
 */
UserLoginRequest.prototype['userPassword'] = undefined;






export default UserLoginRequest;

