/**
 * 毕业设计跳蚤市场
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserBatchDeleteRequest model module.
 * @module model/UserBatchDeleteRequest
 * @version 1.0.0
 */
class UserBatchDeleteRequest {
    /**
     * Constructs a new <code>UserBatchDeleteRequest</code>.
     * 批量删除请求
     * @alias module:model/UserBatchDeleteRequest
     */
    constructor() { 
        
        UserBatchDeleteRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserBatchDeleteRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserBatchDeleteRequest} obj Optional instance to populate.
     * @return {module:model/UserBatchDeleteRequest} The populated <code>UserBatchDeleteRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserBatchDeleteRequest();

            if (data.hasOwnProperty('confirm')) {
                obj['confirm'] = ApiClient.convertToType(data['confirm'], 'Boolean');
            }
            if (data.hasOwnProperty('remark')) {
                obj['remark'] = ApiClient.convertToType(data['remark'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserBatchDeleteRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserBatchDeleteRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['remark'] && !(typeof data['remark'] === 'string' || data['remark'] instanceof String)) {
            throw new Error("Expected the field `remark` to be a primitive type in the JSON string but got " + data['remark']);
        }

        return true;
    }


}



/**
 * @member {Boolean} confirm
 */
UserBatchDeleteRequest.prototype['confirm'] = undefined;

/**
 * @member {String} remark
 */
UserBatchDeleteRequest.prototype['remark'] = undefined;






export default UserBatchDeleteRequest;

