/**
 * 毕业设计跳蚤市场
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenapiJsClient);
  }
}(this, function(expect, OpenapiJsClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenapiJsClient.OrderRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OrderRequest', function() {
    it('should create an instance of OrderRequest', function() {
      // uncomment below and update the code to test OrderRequest
      //var instance = new OpenapiJsClient.OrderRequest();
      //expect(instance).to.be.a(OpenapiJsClient.OrderRequest);
    });

    it('should have the property totalOrders (base name: "totalOrders")', function() {
      // uncomment below and update the code to test the property totalOrders
      //var instance = new OpenapiJsClient.OrderRequest();
      //expect(instance).to.be();
    });

    it('should have the property pendingPaymentOrders (base name: "pendingPaymentOrders")', function() {
      // uncomment below and update the code to test the property pendingPaymentOrders
      //var instance = new OpenapiJsClient.OrderRequest();
      //expect(instance).to.be();
    });

    it('should have the property paidOrders (base name: "paidOrders")', function() {
      // uncomment below and update the code to test the property paidOrders
      //var instance = new OpenapiJsClient.OrderRequest();
      //expect(instance).to.be();
    });

    it('should have the property completedOrders (base name: "completedOrders")', function() {
      // uncomment below and update the code to test the property completedOrders
      //var instance = new OpenapiJsClient.OrderRequest();
      //expect(instance).to.be();
    });

    it('should have the property cancelledOrders (base name: "cancelledOrders")', function() {
      // uncomment below and update the code to test the property cancelledOrders
      //var instance = new OpenapiJsClient.OrderRequest();
      //expect(instance).to.be();
    });

    it('should have the property totalAmount (base name: "totalAmount")', function() {
      // uncomment below and update the code to test the property totalAmount
      //var instance = new OpenapiJsClient.OrderRequest();
      //expect(instance).to.be();
    });

  });

}));
