/**
 * 毕业设计跳蚤市场
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenapiJsClient);
  }
}(this, function(expect, OpenapiJsClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenapiJsClient.Order();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Order', function() {
    it('should create an instance of Order', function() {
      // uncomment below and update the code to test Order
      //var instance = new OpenapiJsClient.Order();
      //expect(instance).to.be.a(OpenapiJsClient.Order);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new OpenapiJsClient.Order();
      //expect(instance).to.be();
    });

    it('should have the property productId (base name: "productId")', function() {
      // uncomment below and update the code to test the property productId
      //var instance = new OpenapiJsClient.Order();
      //expect(instance).to.be();
    });

    it('should have the property buyer (base name: "buyer")', function() {
      // uncomment below and update the code to test the property buyer
      //var instance = new OpenapiJsClient.Order();
      //expect(instance).to.be();
    });

    it('should have the property seller (base name: "seller")', function() {
      // uncomment below and update the code to test the property seller
      //var instance = new OpenapiJsClient.Order();
      //expect(instance).to.be();
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instance = new OpenapiJsClient.Order();
      //expect(instance).to.be();
    });

    it('should have the property paymentMethod (base name: "paymentMethod")', function() {
      // uncomment below and update the code to test the property paymentMethod
      //var instance = new OpenapiJsClient.Order();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new OpenapiJsClient.Order();
      //expect(instance).to.be();
    });

    it('should have the property paymentProof (base name: "paymentProof")', function() {
      // uncomment below and update the code to test the property paymentProof
      //var instance = new OpenapiJsClient.Order();
      //expect(instance).to.be();
    });

    it('should have the property buyerConfirmed (base name: "buyerConfirmed")', function() {
      // uncomment below and update the code to test the property buyerConfirmed
      //var instance = new OpenapiJsClient.Order();
      //expect(instance).to.be();
    });

    it('should have the property sellerConfirmed (base name: "sellerConfirmed")', function() {
      // uncomment below and update the code to test the property sellerConfirmed
      //var instance = new OpenapiJsClient.Order();
      //expect(instance).to.be();
    });

    it('should have the property createTime (base name: "createTime")', function() {
      // uncomment below and update the code to test the property createTime
      //var instance = new OpenapiJsClient.Order();
      //expect(instance).to.be();
    });

    it('should have the property finishTime (base name: "finishTime")', function() {
      // uncomment below and update the code to test the property finishTime
      //var instance = new OpenapiJsClient.Order();
      //expect(instance).to.be();
    });

  });

}));
