/**
 * 毕业设计跳蚤市场
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenapiJsClient);
  }
}(this, function(expect, OpenapiJsClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenapiJsClient.PageOrder();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PageOrder', function() {
    it('should create an instance of PageOrder', function() {
      // uncomment below and update the code to test PageOrder
      //var instance = new OpenapiJsClient.PageOrder();
      //expect(instance).to.be.a(OpenapiJsClient.PageOrder);
    });

    it('should have the property records (base name: "records")', function() {
      // uncomment below and update the code to test the property records
      //var instance = new OpenapiJsClient.PageOrder();
      //expect(instance).to.be();
    });

    it('should have the property total (base name: "total")', function() {
      // uncomment below and update the code to test the property total
      //var instance = new OpenapiJsClient.PageOrder();
      //expect(instance).to.be();
    });

    it('should have the property size (base name: "size")', function() {
      // uncomment below and update the code to test the property size
      //var instance = new OpenapiJsClient.PageOrder();
      //expect(instance).to.be();
    });

    it('should have the property current (base name: "current")', function() {
      // uncomment below and update the code to test the property current
      //var instance = new OpenapiJsClient.PageOrder();
      //expect(instance).to.be();
    });

    it('should have the property orders (base name: "orders")', function() {
      // uncomment below and update the code to test the property orders
      //var instance = new OpenapiJsClient.PageOrder();
      //expect(instance).to.be();
    });

    it('should have the property optimizeCountSql (base name: "optimizeCountSql")', function() {
      // uncomment below and update the code to test the property optimizeCountSql
      //var instance = new OpenapiJsClient.PageOrder();
      //expect(instance).to.be();
    });

    it('should have the property searchCount (base name: "searchCount")', function() {
      // uncomment below and update the code to test the property searchCount
      //var instance = new OpenapiJsClient.PageOrder();
      //expect(instance).to.be();
    });

    it('should have the property optimizeJoinOfCountSql (base name: "optimizeJoinOfCountSql")', function() {
      // uncomment below and update the code to test the property optimizeJoinOfCountSql
      //var instance = new OpenapiJsClient.PageOrder();
      //expect(instance).to.be();
    });

    it('should have the property maxLimit (base name: "maxLimit")', function() {
      // uncomment below and update the code to test the property maxLimit
      //var instance = new OpenapiJsClient.PageOrder();
      //expect(instance).to.be();
    });

    it('should have the property countId (base name: "countId")', function() {
      // uncomment below and update the code to test the property countId
      //var instance = new OpenapiJsClient.PageOrder();
      //expect(instance).to.be();
    });

    it('should have the property pages (base name: "pages")', function() {
      // uncomment below and update the code to test the property pages
      //var instance = new OpenapiJsClient.PageOrder();
      //expect(instance).to.be();
    });

  });

}));
