/**
 * 毕业设计跳蚤市场
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenapiJsClient);
  }
}(this, function(expect, OpenapiJsClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenapiJsClient.ProductRankingItem();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProductRankingItem', function() {
    it('should create an instance of ProductRankingItem', function() {
      // uncomment below and update the code to test ProductRankingItem
      //var instance = new OpenapiJsClient.ProductRankingItem();
      //expect(instance).to.be.a(OpenapiJsClient.ProductRankingItem);
    });

    it('should have the property productId (base name: "productId")', function() {
      // uncomment below and update the code to test the property productId
      //var instance = new OpenapiJsClient.ProductRankingItem();
      //expect(instance).to.be();
    });

    it('should have the property productName (base name: "productName")', function() {
      // uncomment below and update the code to test the property productName
      //var instance = new OpenapiJsClient.ProductRankingItem();
      //expect(instance).to.be();
    });

    it('should have the property tradeCount (base name: "tradeCount")', function() {
      // uncomment below and update the code to test the property tradeCount
      //var instance = new OpenapiJsClient.ProductRankingItem();
      //expect(instance).to.be();
    });

    it('should have the property tradeAmount (base name: "tradeAmount")', function() {
      // uncomment below and update the code to test the property tradeAmount
      //var instance = new OpenapiJsClient.ProductRankingItem();
      //expect(instance).to.be();
    });

    it('should have the property imageUrl (base name: "imageUrl")', function() {
      // uncomment below and update the code to test the property imageUrl
      //var instance = new OpenapiJsClient.ProductRankingItem();
      //expect(instance).to.be();
    });

  });

}));
