/**
 * 毕业设计跳蚤市场
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenapiJsClient);
  }
}(this, function(expect, OpenapiJsClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenapiJsClient.ReviewRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ReviewRequest', function() {
    it('should create an instance of ReviewRequest', function() {
      // uncomment below and update the code to test ReviewRequest
      //var instance = new OpenapiJsClient.ReviewRequest();
      //expect(instance).to.be.a(OpenapiJsClient.ReviewRequest);
    });

    it('should have the property totalReviews (base name: "totalReviews")', function() {
      // uncomment below and update the code to test the property totalReviews
      //var instance = new OpenapiJsClient.ReviewRequest();
      //expect(instance).to.be();
    });

    it('should have the property averageRating (base name: "averageRating")', function() {
      // uncomment below and update the code to test the property averageRating
      //var instance = new OpenapiJsClient.ReviewRequest();
      //expect(instance).to.be();
    });

    it('should have the property fiveStarCount (base name: "fiveStarCount")', function() {
      // uncomment below and update the code to test the property fiveStarCount
      //var instance = new OpenapiJsClient.ReviewRequest();
      //expect(instance).to.be();
    });

    it('should have the property fourStarCount (base name: "fourStarCount")', function() {
      // uncomment below and update the code to test the property fourStarCount
      //var instance = new OpenapiJsClient.ReviewRequest();
      //expect(instance).to.be();
    });

    it('should have the property threeStarCount (base name: "threeStarCount")', function() {
      // uncomment below and update the code to test the property threeStarCount
      //var instance = new OpenapiJsClient.ReviewRequest();
      //expect(instance).to.be();
    });

    it('should have the property twoStarCount (base name: "twoStarCount")', function() {
      // uncomment below and update the code to test the property twoStarCount
      //var instance = new OpenapiJsClient.ReviewRequest();
      //expect(instance).to.be();
    });

    it('should have the property oneStarCount (base name: "oneStarCount")', function() {
      // uncomment below and update the code to test the property oneStarCount
      //var instance = new OpenapiJsClient.ReviewRequest();
      //expect(instance).to.be();
    });

  });

}));
