/**
 * 毕业设计跳蚤市场
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenapiJsClient);
  }
}(this, function(expect, OpenapiJsClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenapiJsClient.StatisticsResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('StatisticsResponse', function() {
    it('should create an instance of StatisticsResponse', function() {
      // uncomment below and update the code to test StatisticsResponse
      //var instance = new OpenapiJsClient.StatisticsResponse();
      //expect(instance).to.be.a(OpenapiJsClient.StatisticsResponse);
    });

    it('should have the property statisticsType (base name: "statisticsType")', function() {
      // uncomment below and update the code to test the property statisticsType
      //var instance = new OpenapiJsClient.StatisticsResponse();
      //expect(instance).to.be();
    });

    it('should have the property statisticsTime (base name: "statisticsTime")', function() {
      // uncomment below and update the code to test the property statisticsTime
      //var instance = new OpenapiJsClient.StatisticsResponse();
      //expect(instance).to.be();
    });

    it('should have the property totalTradeAmount (base name: "totalTradeAmount")', function() {
      // uncomment below and update the code to test the property totalTradeAmount
      //var instance = new OpenapiJsClient.StatisticsResponse();
      //expect(instance).to.be();
    });

    it('should have the property totalTradeCount (base name: "totalTradeCount")', function() {
      // uncomment below and update the code to test the property totalTradeCount
      //var instance = new OpenapiJsClient.StatisticsResponse();
      //expect(instance).to.be();
    });

    it('should have the property monthlyProductRanking (base name: "monthlyProductRanking")', function() {
      // uncomment below and update the code to test the property monthlyProductRanking
      //var instance = new OpenapiJsClient.StatisticsResponse();
      //expect(instance).to.be();
    });

    it('should have the property activeUserRanking (base name: "activeUserRanking")', function() {
      // uncomment below and update the code to test the property activeUserRanking
      //var instance = new OpenapiJsClient.StatisticsResponse();
      //expect(instance).to.be();
    });

    it('should have the property highDemandRanking (base name: "highDemandRanking")', function() {
      // uncomment below and update the code to test the property highDemandRanking
      //var instance = new OpenapiJsClient.StatisticsResponse();
      //expect(instance).to.be();
    });

    it('should have the property highInventoryRanking (base name: "highInventoryRanking")', function() {
      // uncomment below and update the code to test the property highInventoryRanking
      //var instance = new OpenapiJsClient.StatisticsResponse();
      //expect(instance).to.be();
    });

  });

}));
