/**
 * 毕业设计跳蚤市场
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenapiJsClient);
  }
}(this, function(expect, OpenapiJsClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenapiJsClient.TradeRecord();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TradeRecord', function() {
    it('should create an instance of TradeRecord', function() {
      // uncomment below and update the code to test TradeRecord
      //var instance = new OpenapiJsClient.TradeRecord();
      //expect(instance).to.be.a(OpenapiJsClient.TradeRecord);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new OpenapiJsClient.TradeRecord();
      //expect(instance).to.be();
    });

    it('should have the property orderId (base name: "orderId")', function() {
      // uncomment below and update the code to test the property orderId
      //var instance = new OpenapiJsClient.TradeRecord();
      //expect(instance).to.be();
    });

    it('should have the property productId (base name: "productId")', function() {
      // uncomment below and update the code to test the property productId
      //var instance = new OpenapiJsClient.TradeRecord();
      //expect(instance).to.be();
    });

    it('should have the property productName (base name: "productName")', function() {
      // uncomment below and update the code to test the property productName
      //var instance = new OpenapiJsClient.TradeRecord();
      //expect(instance).to.be();
    });

    it('should have the property buyerId (base name: "buyerId")', function() {
      // uncomment below and update the code to test the property buyerId
      //var instance = new OpenapiJsClient.TradeRecord();
      //expect(instance).to.be();
    });

    it('should have the property buyerName (base name: "buyerName")', function() {
      // uncomment below and update the code to test the property buyerName
      //var instance = new OpenapiJsClient.TradeRecord();
      //expect(instance).to.be();
    });

    it('should have the property sellerId (base name: "sellerId")', function() {
      // uncomment below and update the code to test the property sellerId
      //var instance = new OpenapiJsClient.TradeRecord();
      //expect(instance).to.be();
    });

    it('should have the property sellerName (base name: "sellerName")', function() {
      // uncomment below and update the code to test the property sellerName
      //var instance = new OpenapiJsClient.TradeRecord();
      //expect(instance).to.be();
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instance = new OpenapiJsClient.TradeRecord();
      //expect(instance).to.be();
    });

    it('should have the property paymentMethod (base name: "paymentMethod")', function() {
      // uncomment below and update the code to test the property paymentMethod
      //var instance = new OpenapiJsClient.TradeRecord();
      //expect(instance).to.be();
    });

    it('should have the property paymentMethodDesc (base name: "paymentMethodDesc")', function() {
      // uncomment below and update the code to test the property paymentMethodDesc
      //var instance = new OpenapiJsClient.TradeRecord();
      //expect(instance).to.be();
    });

    it('should have the property tradeTime (base name: "tradeTime")', function() {
      // uncomment below and update the code to test the property tradeTime
      //var instance = new OpenapiJsClient.TradeRecord();
      //expect(instance).to.be();
    });

    it('should have the property tradeStatus (base name: "tradeStatus")', function() {
      // uncomment below and update the code to test the property tradeStatus
      //var instance = new OpenapiJsClient.TradeRecord();
      //expect(instance).to.be();
    });

    it('should have the property remark (base name: "remark")', function() {
      // uncomment below and update the code to test the property remark
      //var instance = new OpenapiJsClient.TradeRecord();
      //expect(instance).to.be();
    });

    it('should have the property reviewId (base name: "reviewId")', function() {
      // uncomment below and update the code to test the property reviewId
      //var instance = new OpenapiJsClient.TradeRecord();
      //expect(instance).to.be();
    });

  });

}));
