/**
 * 毕业设计跳蚤市场
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenapiJsClient);
  }
}(this, function(expect, OpenapiJsClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenapiJsClient.UserVo();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UserVo', function() {
    it('should create an instance of UserVo', function() {
      // uncomment below and update the code to test UserVo
      //var instance = new OpenapiJsClient.UserVo();
      //expect(instance).to.be.a(OpenapiJsClient.UserVo);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new OpenapiJsClient.UserVo();
      //expect(instance).to.be();
    });

    it('should have the property userName (base name: "userName")', function() {
      // uncomment below and update the code to test the property userName
      //var instance = new OpenapiJsClient.UserVo();
      //expect(instance).to.be();
    });

    it('should have the property userAvatar (base name: "userAvatar")', function() {
      // uncomment below and update the code to test the property userAvatar
      //var instance = new OpenapiJsClient.UserVo();
      //expect(instance).to.be();
    });

    it('should have the property userRole (base name: "userRole")', function() {
      // uncomment below and update the code to test the property userRole
      //var instance = new OpenapiJsClient.UserVo();
      //expect(instance).to.be();
    });

    it('should have the property point (base name: "point")', function() {
      // uncomment below and update the code to test the property point
      //var instance = new OpenapiJsClient.UserVo();
      //expect(instance).to.be();
    });

    it('should have the property registerTime (base name: "registerTime")', function() {
      // uncomment below and update the code to test the property registerTime
      //var instance = new OpenapiJsClient.UserVo();
      //expect(instance).to.be();
    });

  });

}));
