/**
 * 毕业设计跳蚤市场
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenapiJsClient);
  }
}(this, function(expect, OpenapiJsClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenapiJsClient.UserAddRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UserAddRequest', function() {
    it('should create an instance of UserAddRequest', function() {
      // uncomment below and update the code to test UserAddRequest
      //var instance = new OpenapiJsClient.UserAddRequest();
      //expect(instance).to.be.a(OpenapiJsClient.UserAddRequest);
    });

    it('should have the property userName (base name: "userName")', function() {
      // uncomment below and update the code to test the property userName
      //var instance = new OpenapiJsClient.UserAddRequest();
      //expect(instance).to.be();
    });

    it('should have the property userAccount (base name: "userAccount")', function() {
      // uncomment below and update the code to test the property userAccount
      //var instance = new OpenapiJsClient.UserAddRequest();
      //expect(instance).to.be();
    });

    it('should have the property userAvatar (base name: "userAvatar")', function() {
      // uncomment below and update the code to test the property userAvatar
      //var instance = new OpenapiJsClient.UserAddRequest();
      //expect(instance).to.be();
    });

    it('should have the property userPhone (base name: "userPhone")', function() {
      // uncomment below and update the code to test the property userPhone
      //var instance = new OpenapiJsClient.UserAddRequest();
      //expect(instance).to.be();
    });

    it('should have the property userRole (base name: "userRole")', function() {
      // uncomment below and update the code to test the property userRole
      //var instance = new OpenapiJsClient.UserAddRequest();
      //expect(instance).to.be();
    });

  });

}));
