/**
 * 毕业设计跳蚤市场
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import BaseResponseBoolean from './model/BaseResponseBoolean';
import BaseResponseCategory from './model/BaseResponseCategory';
import BaseResponseDouble from './model/BaseResponseDouble';
import BaseResponseInteger from './model/BaseResponseInteger';
import BaseResponseListCategory from './model/BaseResponseListCategory';
import BaseResponseListNews from './model/BaseResponseListNews';
import BaseResponseListProduct from './model/BaseResponseListProduct';
import BaseResponseListProductRankingItem from './model/BaseResponseListProductRankingItem';
import BaseResponseListUserRankingItem from './model/BaseResponseListUserRankingItem';
import BaseResponseListUserVo from './model/BaseResponseListUserVo';
import BaseResponseLoginUserVo from './model/BaseResponseLoginUserVo';
import BaseResponseLong from './model/BaseResponseLong';
import BaseResponseNews from './model/BaseResponseNews';
import BaseResponseOrder from './model/BaseResponseOrder';
import BaseResponseOrderRequest from './model/BaseResponseOrderRequest';
import BaseResponsePageCategory from './model/BaseResponsePageCategory';
import BaseResponsePageOrder from './model/BaseResponsePageOrder';
import BaseResponsePageProduct from './model/BaseResponsePageProduct';
import BaseResponsePageReview from './model/BaseResponsePageReview';
import BaseResponsePageTradeRecord from './model/BaseResponsePageTradeRecord';
import BaseResponsePageUser from './model/BaseResponsePageUser';
import BaseResponsePageUserVo from './model/BaseResponsePageUserVo';
import BaseResponseProduct from './model/BaseResponseProduct';
import BaseResponseReview from './model/BaseResponseReview';
import BaseResponseReviewRequest from './model/BaseResponseReviewRequest';
import BaseResponseStatisticsResponse from './model/BaseResponseStatisticsResponse';
import BaseResponseString from './model/BaseResponseString';
import BaseResponseTradeRecord from './model/BaseResponseTradeRecord';
import BaseResponseUser from './model/BaseResponseUser';
import BaseResponseUserVo from './model/BaseResponseUserVo';
import Category from './model/Category';
import CategoryAddRequest from './model/CategoryAddRequest';
import CategoryUpdateRequest from './model/CategoryUpdateRequest';
import DeleteRequest from './model/DeleteRequest';
import LoginUserVo from './model/LoginUserVo';
import News from './model/News';
import NewsAddRequest from './model/NewsAddRequest';
import NewsUpdateRequest from './model/NewsUpdateRequest';
import Order from './model/Order';
import OrderConfirmRequest from './model/OrderConfirmRequest';
import OrderItem from './model/OrderItem';
import OrderRequest from './model/OrderRequest';
import PageCategory from './model/PageCategory';
import PageOrder from './model/PageOrder';
import PageProduct from './model/PageProduct';
import PageRequest from './model/PageRequest';
import PageReview from './model/PageReview';
import PageTradeRecord from './model/PageTradeRecord';
import PageUser from './model/PageUser';
import PageUserVo from './model/PageUserVo';
import PaymentProofRequest from './model/PaymentProofRequest';
import Product from './model/Product';
import ProductAddRequest from './model/ProductAddRequest';
import ProductRankingItem from './model/ProductRankingItem';
import ProductUpdateRequest from './model/ProductUpdateRequest';
import Review from './model/Review';
import ReviewRequest from './model/ReviewRequest';
import StatisticsResponse from './model/StatisticsResponse';
import TradeRecord from './model/TradeRecord';
import User from './model/User';
import UserAddRequest from './model/UserAddRequest';
import UserAuditRequest from './model/UserAuditRequest';
import UserBatchDeleteRequest from './model/UserBatchDeleteRequest';
import UserLoginRequest from './model/UserLoginRequest';
import UserQueryRequest from './model/UserQueryRequest';
import UserRankingItem from './model/UserRankingItem';
import UserRegisterRequest from './model/UserRegisterRequest';
import UserUpdateMyRequest from './model/UserUpdateMyRequest';
import UserUpdateRequest from './model/UserUpdateRequest';
import UserVo from './model/UserVo';
import DefaultApi from './api/DefaultApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var OpenapiJsClient = require('index'); // See note below*.
* var xxxSvc = new OpenapiJsClient.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new OpenapiJsClient.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new OpenapiJsClient.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new OpenapiJsClient.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The BaseResponseBoolean model constructor.
     * @property {module:model/BaseResponseBoolean}
     */
    BaseResponseBoolean,

    /**
     * The BaseResponseCategory model constructor.
     * @property {module:model/BaseResponseCategory}
     */
    BaseResponseCategory,

    /**
     * The BaseResponseDouble model constructor.
     * @property {module:model/BaseResponseDouble}
     */
    BaseResponseDouble,

    /**
     * The BaseResponseInteger model constructor.
     * @property {module:model/BaseResponseInteger}
     */
    BaseResponseInteger,

    /**
     * The BaseResponseListCategory model constructor.
     * @property {module:model/BaseResponseListCategory}
     */
    BaseResponseListCategory,

    /**
     * The BaseResponseListNews model constructor.
     * @property {module:model/BaseResponseListNews}
     */
    BaseResponseListNews,

    /**
     * The BaseResponseListProduct model constructor.
     * @property {module:model/BaseResponseListProduct}
     */
    BaseResponseListProduct,

    /**
     * The BaseResponseListProductRankingItem model constructor.
     * @property {module:model/BaseResponseListProductRankingItem}
     */
    BaseResponseListProductRankingItem,

    /**
     * The BaseResponseListUserRankingItem model constructor.
     * @property {module:model/BaseResponseListUserRankingItem}
     */
    BaseResponseListUserRankingItem,

    /**
     * The BaseResponseListUserVo model constructor.
     * @property {module:model/BaseResponseListUserVo}
     */
    BaseResponseListUserVo,

    /**
     * The BaseResponseLoginUserVo model constructor.
     * @property {module:model/BaseResponseLoginUserVo}
     */
    BaseResponseLoginUserVo,

    /**
     * The BaseResponseLong model constructor.
     * @property {module:model/BaseResponseLong}
     */
    BaseResponseLong,

    /**
     * The BaseResponseNews model constructor.
     * @property {module:model/BaseResponseNews}
     */
    BaseResponseNews,

    /**
     * The BaseResponseOrder model constructor.
     * @property {module:model/BaseResponseOrder}
     */
    BaseResponseOrder,

    /**
     * The BaseResponseOrderRequest model constructor.
     * @property {module:model/BaseResponseOrderRequest}
     */
    BaseResponseOrderRequest,

    /**
     * The BaseResponsePageCategory model constructor.
     * @property {module:model/BaseResponsePageCategory}
     */
    BaseResponsePageCategory,

    /**
     * The BaseResponsePageOrder model constructor.
     * @property {module:model/BaseResponsePageOrder}
     */
    BaseResponsePageOrder,

    /**
     * The BaseResponsePageProduct model constructor.
     * @property {module:model/BaseResponsePageProduct}
     */
    BaseResponsePageProduct,

    /**
     * The BaseResponsePageReview model constructor.
     * @property {module:model/BaseResponsePageReview}
     */
    BaseResponsePageReview,

    /**
     * The BaseResponsePageTradeRecord model constructor.
     * @property {module:model/BaseResponsePageTradeRecord}
     */
    BaseResponsePageTradeRecord,

    /**
     * The BaseResponsePageUser model constructor.
     * @property {module:model/BaseResponsePageUser}
     */
    BaseResponsePageUser,

    /**
     * The BaseResponsePageUserVo model constructor.
     * @property {module:model/BaseResponsePageUserVo}
     */
    BaseResponsePageUserVo,

    /**
     * The BaseResponseProduct model constructor.
     * @property {module:model/BaseResponseProduct}
     */
    BaseResponseProduct,

    /**
     * The BaseResponseReview model constructor.
     * @property {module:model/BaseResponseReview}
     */
    BaseResponseReview,

    /**
     * The BaseResponseReviewRequest model constructor.
     * @property {module:model/BaseResponseReviewRequest}
     */
    BaseResponseReviewRequest,

    /**
     * The BaseResponseStatisticsResponse model constructor.
     * @property {module:model/BaseResponseStatisticsResponse}
     */
    BaseResponseStatisticsResponse,

    /**
     * The BaseResponseString model constructor.
     * @property {module:model/BaseResponseString}
     */
    BaseResponseString,

    /**
     * The BaseResponseTradeRecord model constructor.
     * @property {module:model/BaseResponseTradeRecord}
     */
    BaseResponseTradeRecord,

    /**
     * The BaseResponseUser model constructor.
     * @property {module:model/BaseResponseUser}
     */
    BaseResponseUser,

    /**
     * The BaseResponseUserVo model constructor.
     * @property {module:model/BaseResponseUserVo}
     */
    BaseResponseUserVo,

    /**
     * The Category model constructor.
     * @property {module:model/Category}
     */
    Category,

    /**
     * The CategoryAddRequest model constructor.
     * @property {module:model/CategoryAddRequest}
     */
    CategoryAddRequest,

    /**
     * The CategoryUpdateRequest model constructor.
     * @property {module:model/CategoryUpdateRequest}
     */
    CategoryUpdateRequest,

    /**
     * The DeleteRequest model constructor.
     * @property {module:model/DeleteRequest}
     */
    DeleteRequest,

    /**
     * The LoginUserVo model constructor.
     * @property {module:model/LoginUserVo}
     */
    LoginUserVo,

    /**
     * The News model constructor.
     * @property {module:model/News}
     */
    News,

    /**
     * The NewsAddRequest model constructor.
     * @property {module:model/NewsAddRequest}
     */
    NewsAddRequest,

    /**
     * The NewsUpdateRequest model constructor.
     * @property {module:model/NewsUpdateRequest}
     */
    NewsUpdateRequest,

    /**
     * The Order model constructor.
     * @property {module:model/Order}
     */
    Order,

    /**
     * The OrderConfirmRequest model constructor.
     * @property {module:model/OrderConfirmRequest}
     */
    OrderConfirmRequest,

    /**
     * The OrderItem model constructor.
     * @property {module:model/OrderItem}
     */
    OrderItem,

    /**
     * The OrderRequest model constructor.
     * @property {module:model/OrderRequest}
     */
    OrderRequest,

    /**
     * The PageCategory model constructor.
     * @property {module:model/PageCategory}
     */
    PageCategory,

    /**
     * The PageOrder model constructor.
     * @property {module:model/PageOrder}
     */
    PageOrder,

    /**
     * The PageProduct model constructor.
     * @property {module:model/PageProduct}
     */
    PageProduct,

    /**
     * The PageRequest model constructor.
     * @property {module:model/PageRequest}
     */
    PageRequest,

    /**
     * The PageReview model constructor.
     * @property {module:model/PageReview}
     */
    PageReview,

    /**
     * The PageTradeRecord model constructor.
     * @property {module:model/PageTradeRecord}
     */
    PageTradeRecord,

    /**
     * The PageUser model constructor.
     * @property {module:model/PageUser}
     */
    PageUser,

    /**
     * The PageUserVo model constructor.
     * @property {module:model/PageUserVo}
     */
    PageUserVo,

    /**
     * The PaymentProofRequest model constructor.
     * @property {module:model/PaymentProofRequest}
     */
    PaymentProofRequest,

    /**
     * The Product model constructor.
     * @property {module:model/Product}
     */
    Product,

    /**
     * The ProductAddRequest model constructor.
     * @property {module:model/ProductAddRequest}
     */
    ProductAddRequest,

    /**
     * The ProductRankingItem model constructor.
     * @property {module:model/ProductRankingItem}
     */
    ProductRankingItem,

    /**
     * The ProductUpdateRequest model constructor.
     * @property {module:model/ProductUpdateRequest}
     */
    ProductUpdateRequest,

    /**
     * The Review model constructor.
     * @property {module:model/Review}
     */
    Review,

    /**
     * The ReviewRequest model constructor.
     * @property {module:model/ReviewRequest}
     */
    ReviewRequest,

    /**
     * The StatisticsResponse model constructor.
     * @property {module:model/StatisticsResponse}
     */
    StatisticsResponse,

    /**
     * The TradeRecord model constructor.
     * @property {module:model/TradeRecord}
     */
    TradeRecord,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
     * The UserAddRequest model constructor.
     * @property {module:model/UserAddRequest}
     */
    UserAddRequest,

    /**
     * The UserAuditRequest model constructor.
     * @property {module:model/UserAuditRequest}
     */
    UserAuditRequest,

    /**
     * The UserBatchDeleteRequest model constructor.
     * @property {module:model/UserBatchDeleteRequest}
     */
    UserBatchDeleteRequest,

    /**
     * The UserLoginRequest model constructor.
     * @property {module:model/UserLoginRequest}
     */
    UserLoginRequest,

    /**
     * The UserQueryRequest model constructor.
     * @property {module:model/UserQueryRequest}
     */
    UserQueryRequest,

    /**
     * The UserRankingItem model constructor.
     * @property {module:model/UserRankingItem}
     */
    UserRankingItem,

    /**
     * The UserRegisterRequest model constructor.
     * @property {module:model/UserRegisterRequest}
     */
    UserRegisterRequest,

    /**
     * The UserUpdateMyRequest model constructor.
     * @property {module:model/UserUpdateMyRequest}
     */
    UserUpdateMyRequest,

    /**
     * The UserUpdateRequest model constructor.
     * @property {module:model/UserUpdateRequest}
     */
    UserUpdateRequest,

    /**
     * The UserVo model constructor.
     * @property {module:model/UserVo}
     */
    UserVo,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
