/**
 * 毕业设计跳蚤市场
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenapiJsClient);
  }
}(this, function(expect, OpenapiJsClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenapiJsClient.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('addCategory', function() {
      it('should call addCategory successfully', function(done) {
        //uncomment below and update the code to test addCategory
        //instance.addCategory(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addCategory_0', function() {
      it('should call addCategory_0 successfully', function(done) {
        //uncomment below and update the code to test addCategory_0
        //instance.addCategory_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addNews', function() {
      it('should call addNews successfully', function(done) {
        //uncomment below and update the code to test addNews
        //instance.addNews(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addNews_0', function() {
      it('should call addNews_0 successfully', function(done) {
        //uncomment below and update the code to test addNews_0
        //instance.addNews_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addProduct', function() {
      it('should call addProduct successfully', function(done) {
        //uncomment below and update the code to test addProduct
        //instance.addProduct(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addProduct_0', function() {
      it('should call addProduct_0 successfully', function(done) {
        //uncomment below and update the code to test addProduct_0
        //instance.addProduct_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addReview', function() {
      it('should call addReview successfully', function(done) {
        //uncomment below and update the code to test addReview
        //instance.addReview(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addReview_0', function() {
      it('should call addReview_0 successfully', function(done) {
        //uncomment below and update the code to test addReview_0
        //instance.addReview_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addUser', function() {
      it('should call addUser successfully', function(done) {
        //uncomment below and update the code to test addUser
        //instance.addUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addUser_0', function() {
      it('should call addUser_0 successfully', function(done) {
        //uncomment below and update the code to test addUser_0
        //instance.addUser_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('adminListOrders', function() {
      it('should call adminListOrders successfully', function(done) {
        //uncomment below and update the code to test adminListOrders
        //instance.adminListOrders(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('adminListOrders_0', function() {
      it('should call adminListOrders_0 successfully', function(done) {
        //uncomment below and update the code to test adminListOrders_0
        //instance.adminListOrders_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('adminListProducts', function() {
      it('should call adminListProducts successfully', function(done) {
        //uncomment below and update the code to test adminListProducts
        //instance.adminListProducts(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('adminListProducts_0', function() {
      it('should call adminListProducts_0 successfully', function(done) {
        //uncomment below and update the code to test adminListProducts_0
        //instance.adminListProducts_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('adminListReviews', function() {
      it('should call adminListReviews successfully', function(done) {
        //uncomment below and update the code to test adminListReviews
        //instance.adminListReviews(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('adminListReviews_0', function() {
      it('should call adminListReviews_0 successfully', function(done) {
        //uncomment below and update the code to test adminListReviews_0
        //instance.adminListReviews_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('adminListTradeRecords', function() {
      it('should call adminListTradeRecords successfully', function(done) {
        //uncomment below and update the code to test adminListTradeRecords
        //instance.adminListTradeRecords(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('adminListTradeRecords_0', function() {
      it('should call adminListTradeRecords_0 successfully', function(done) {
        //uncomment below and update the code to test adminListTradeRecords_0
        //instance.adminListTradeRecords_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('advancedSearchProducts', function() {
      it('should call advancedSearchProducts successfully', function(done) {
        //uncomment below and update the code to test advancedSearchProducts
        //instance.advancedSearchProducts(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('advancedSearchProducts_0', function() {
      it('should call advancedSearchProducts_0 successfully', function(done) {
        //uncomment below and update the code to test advancedSearchProducts_0
        //instance.advancedSearchProducts_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('applyForExchange', function() {
      it('should call applyForExchange successfully', function(done) {
        //uncomment below and update the code to test applyForExchange
        //instance.applyForExchange(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('applyForExchange_0', function() {
      it('should call applyForExchange_0 successfully', function(done) {
        //uncomment below and update the code to test applyForExchange_0
        //instance.applyForExchange_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('auditUser', function() {
      it('should call auditUser successfully', function(done) {
        //uncomment below and update the code to test auditUser
        //instance.auditUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('auditUser_0', function() {
      it('should call auditUser_0 successfully', function(done) {
        //uncomment below and update the code to test auditUser_0
        //instance.auditUser_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('batchDeleteRejectedUsers', function() {
      it('should call batchDeleteRejectedUsers successfully', function(done) {
        //uncomment below and update the code to test batchDeleteRejectedUsers
        //instance.batchDeleteRejectedUsers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('batchDeleteRejectedUsers_0', function() {
      it('should call batchDeleteRejectedUsers_0 successfully', function(done) {
        //uncomment below and update the code to test batchDeleteRejectedUsers_0
        //instance.batchDeleteRejectedUsers_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('cancelOrder', function() {
      it('should call cancelOrder successfully', function(done) {
        //uncomment below and update the code to test cancelOrder
        //instance.cancelOrder(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('cancelOrder_0', function() {
      it('should call cancelOrder_0 successfully', function(done) {
        //uncomment below and update the code to test cancelOrder_0
        //instance.cancelOrder_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('completeOrder', function() {
      it('should call completeOrder successfully', function(done) {
        //uncomment below and update the code to test completeOrder
        //instance.completeOrder(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('completeOrder_0', function() {
      it('should call completeOrder_0 successfully', function(done) {
        //uncomment below and update the code to test completeOrder_0
        //instance.completeOrder_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('confirmExchange', function() {
      it('should call confirmExchange successfully', function(done) {
        //uncomment below and update the code to test confirmExchange
        //instance.confirmExchange(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('confirmExchange_0', function() {
      it('should call confirmExchange_0 successfully', function(done) {
        //uncomment below and update the code to test confirmExchange_0
        //instance.confirmExchange_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('confirmOrder', function() {
      it('should call confirmOrder successfully', function(done) {
        //uncomment below and update the code to test confirmOrder
        //instance.confirmOrder(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('confirmOrder_0', function() {
      it('should call confirmOrder_0 successfully', function(done) {
        //uncomment below and update the code to test confirmOrder_0
        //instance.confirmOrder_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createOrder', function() {
      it('should call createOrder successfully', function(done) {
        //uncomment below and update the code to test createOrder
        //instance.createOrder(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createOrder_0', function() {
      it('should call createOrder_0 successfully', function(done) {
        //uncomment below and update the code to test createOrder_0
        //instance.createOrder_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteCategory', function() {
      it('should call deleteCategory successfully', function(done) {
        //uncomment below and update the code to test deleteCategory
        //instance.deleteCategory(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteCategory_0', function() {
      it('should call deleteCategory_0 successfully', function(done) {
        //uncomment below and update the code to test deleteCategory_0
        //instance.deleteCategory_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteNews', function() {
      it('should call deleteNews successfully', function(done) {
        //uncomment below and update the code to test deleteNews
        //instance.deleteNews(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteNews_0', function() {
      it('should call deleteNews_0 successfully', function(done) {
        //uncomment below and update the code to test deleteNews_0
        //instance.deleteNews_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteProduct', function() {
      it('should call deleteProduct successfully', function(done) {
        //uncomment below and update the code to test deleteProduct
        //instance.deleteProduct(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteProduct_0', function() {
      it('should call deleteProduct_0 successfully', function(done) {
        //uncomment below and update the code to test deleteProduct_0
        //instance.deleteProduct_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteReview', function() {
      it('should call deleteReview successfully', function(done) {
        //uncomment below and update the code to test deleteReview
        //instance.deleteReview(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteReview_0', function() {
      it('should call deleteReview_0 successfully', function(done) {
        //uncomment below and update the code to test deleteReview_0
        //instance.deleteReview_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteUser', function() {
      it('should call deleteUser successfully', function(done) {
        //uncomment below and update the code to test deleteUser
        //instance.deleteUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteUser_0', function() {
      it('should call deleteUser_0 successfully', function(done) {
        //uncomment below and update the code to test deleteUser_0
        //instance.deleteUser_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('exchangeWithPoints', function() {
      it('should call exchangeWithPoints successfully', function(done) {
        //uncomment below and update the code to test exchangeWithPoints
        //instance.exchangeWithPoints(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('exchangeWithPoints_0', function() {
      it('should call exchangeWithPoints_0 successfully', function(done) {
        //uncomment below and update the code to test exchangeWithPoints_0
        //instance.exchangeWithPoints_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getActiveUsersRanking', function() {
      it('should call getActiveUsersRanking successfully', function(done) {
        //uncomment below and update the code to test getActiveUsersRanking
        //instance.getActiveUsersRanking(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getActiveUsersRanking_0', function() {
      it('should call getActiveUsersRanking_0 successfully', function(done) {
        //uncomment below and update the code to test getActiveUsersRanking_0
        //instance.getActiveUsersRanking_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAverageRating', function() {
      it('should call getAverageRating successfully', function(done) {
        //uncomment below and update the code to test getAverageRating
        //instance.getAverageRating(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAverageRating_0', function() {
      it('should call getAverageRating_0 successfully', function(done) {
        //uncomment below and update the code to test getAverageRating_0
        //instance.getAverageRating_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCategoryList', function() {
      it('should call getCategoryList successfully', function(done) {
        //uncomment below and update the code to test getCategoryList
        //instance.getCategoryList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCategoryList_0', function() {
      it('should call getCategoryList_0 successfully', function(done) {
        //uncomment below and update the code to test getCategoryList_0
        //instance.getCategoryList_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getComprehensiveStatistics', function() {
      it('should call getComprehensiveStatistics successfully', function(done) {
        //uncomment below and update the code to test getComprehensiveStatistics
        //instance.getComprehensiveStatistics(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getComprehensiveStatistics_0', function() {
      it('should call getComprehensiveStatistics_0 successfully', function(done) {
        //uncomment below and update the code to test getComprehensiveStatistics_0
        //instance.getComprehensiveStatistics_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getHighDemandProducts', function() {
      it('should call getHighDemandProducts successfully', function(done) {
        //uncomment below and update the code to test getHighDemandProducts
        //instance.getHighDemandProducts(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getHighDemandProducts_0', function() {
      it('should call getHighDemandProducts_0 successfully', function(done) {
        //uncomment below and update the code to test getHighDemandProducts_0
        //instance.getHighDemandProducts_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getHighInventoryProducts', function() {
      it('should call getHighInventoryProducts successfully', function(done) {
        //uncomment below and update the code to test getHighInventoryProducts
        //instance.getHighInventoryProducts(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getHighInventoryProducts_0', function() {
      it('should call getHighInventoryProducts_0 successfully', function(done) {
        //uncomment below and update the code to test getHighInventoryProducts_0
        //instance.getHighInventoryProducts_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLatestNews', function() {
      it('should call getLatestNews successfully', function(done) {
        //uncomment below and update the code to test getLatestNews
        //instance.getLatestNews(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLatestNews_0', function() {
      it('should call getLatestNews_0 successfully', function(done) {
        //uncomment below and update the code to test getLatestNews_0
        //instance.getLatestNews_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLatestProducts', function() {
      it('should call getLatestProducts successfully', function(done) {
        //uncomment below and update the code to test getLatestProducts
        //instance.getLatestProducts(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLatestProducts_0', function() {
      it('should call getLatestProducts_0 successfully', function(done) {
        //uncomment below and update the code to test getLatestProducts_0
        //instance.getLatestProducts_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLoginUser', function() {
      it('should call getLoginUser successfully', function(done) {
        //uncomment below and update the code to test getLoginUser
        //instance.getLoginUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLoginUser_0', function() {
      it('should call getLoginUser_0 successfully', function(done) {
        //uncomment below and update the code to test getLoginUser_0
        //instance.getLoginUser_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMonthlyStatistics', function() {
      it('should call getMonthlyStatistics successfully', function(done) {
        //uncomment below and update the code to test getMonthlyStatistics
        //instance.getMonthlyStatistics(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMonthlyStatistics_0', function() {
      it('should call getMonthlyStatistics_0 successfully', function(done) {
        //uncomment below and update the code to test getMonthlyStatistics_0
        //instance.getMonthlyStatistics_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMonthlyTopSellingProducts', function() {
      it('should call getMonthlyTopSellingProducts successfully', function(done) {
        //uncomment below and update the code to test getMonthlyTopSellingProducts
        //instance.getMonthlyTopSellingProducts(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMonthlyTopSellingProducts_0', function() {
      it('should call getMonthlyTopSellingProducts_0 successfully', function(done) {
        //uncomment below and update the code to test getMonthlyTopSellingProducts_0
        //instance.getMonthlyTopSellingProducts_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMyReviewForProduct', function() {
      it('should call getMyReviewForProduct successfully', function(done) {
        //uncomment below and update the code to test getMyReviewForProduct
        //instance.getMyReviewForProduct(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMyReviewForProduct_0', function() {
      it('should call getMyReviewForProduct_0 successfully', function(done) {
        //uncomment below and update the code to test getMyReviewForProduct_0
        //instance.getMyReviewForProduct_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getNewsDetail', function() {
      it('should call getNewsDetail successfully', function(done) {
        //uncomment below and update the code to test getNewsDetail
        //instance.getNewsDetail(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getNewsDetail_0', function() {
      it('should call getNewsDetail_0 successfully', function(done) {
        //uncomment below and update the code to test getNewsDetail_0
        //instance.getNewsDetail_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getNewsList', function() {
      it('should call getNewsList successfully', function(done) {
        //uncomment below and update the code to test getNewsList
        //instance.getNewsList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getNewsList_0', function() {
      it('should call getNewsList_0 successfully', function(done) {
        //uncomment below and update the code to test getNewsList_0
        //instance.getNewsList_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOrderById', function() {
      it('should call getOrderById successfully', function(done) {
        //uncomment below and update the code to test getOrderById
        //instance.getOrderById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOrderById_0', function() {
      it('should call getOrderById_0 successfully', function(done) {
        //uncomment below and update the code to test getOrderById_0
        //instance.getOrderById_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOrderStatistics', function() {
      it('should call getOrderStatistics successfully', function(done) {
        //uncomment below and update the code to test getOrderStatistics
        //instance.getOrderStatistics(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOrderStatistics_0', function() {
      it('should call getOrderStatistics_0 successfully', function(done) {
        //uncomment below and update the code to test getOrderStatistics_0
        //instance.getOrderStatistics_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPendingAuditUsers', function() {
      it('should call getPendingAuditUsers successfully', function(done) {
        //uncomment below and update the code to test getPendingAuditUsers
        //instance.getPendingAuditUsers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPendingAuditUsers_0', function() {
      it('should call getPendingAuditUsers_0 successfully', function(done) {
        //uncomment below and update the code to test getPendingAuditUsers_0
        //instance.getPendingAuditUsers_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getProductById', function() {
      it('should call getProductById successfully', function(done) {
        //uncomment below and update the code to test getProductById
        //instance.getProductById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getProductById_0', function() {
      it('should call getProductById_0 successfully', function(done) {
        //uncomment below and update the code to test getProductById_0
        //instance.getProductById_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getProductTradeStatistics', function() {
      it('should call getProductTradeStatistics successfully', function(done) {
        //uncomment below and update the code to test getProductTradeStatistics
        //instance.getProductTradeStatistics(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getProductTradeStatistics_0', function() {
      it('should call getProductTradeStatistics_0 successfully', function(done) {
        //uncomment below and update the code to test getProductTradeStatistics_0
        //instance.getProductTradeStatistics_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getRejectedUserCount', function() {
      it('should call getRejectedUserCount successfully', function(done) {
        //uncomment below and update the code to test getRejectedUserCount
        //instance.getRejectedUserCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getRejectedUserCount_0', function() {
      it('should call getRejectedUserCount_0 successfully', function(done) {
        //uncomment below and update the code to test getRejectedUserCount_0
        //instance.getRejectedUserCount_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getReviewById', function() {
      it('should call getReviewById successfully', function(done) {
        //uncomment below and update the code to test getReviewById
        //instance.getReviewById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getReviewById_0', function() {
      it('should call getReviewById_0 successfully', function(done) {
        //uncomment below and update the code to test getReviewById_0
        //instance.getReviewById_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getReviewStatistics', function() {
      it('should call getReviewStatistics successfully', function(done) {
        //uncomment below and update the code to test getReviewStatistics
        //instance.getReviewStatistics(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getReviewStatistics_0', function() {
      it('should call getReviewStatistics_0 successfully', function(done) {
        //uncomment below and update the code to test getReviewStatistics_0
        //instance.getReviewStatistics_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTradeRecordDetail', function() {
      it('should call getTradeRecordDetail successfully', function(done) {
        //uncomment below and update the code to test getTradeRecordDetail
        //instance.getTradeRecordDetail(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTradeRecordDetail_0', function() {
      it('should call getTradeRecordDetail_0 successfully', function(done) {
        //uncomment below and update the code to test getTradeRecordDetail_0
        //instance.getTradeRecordDetail_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserById', function() {
      it('should call getUserById successfully', function(done) {
        //uncomment below and update the code to test getUserById
        //instance.getUserById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserById_0', function() {
      it('should call getUserById_0 successfully', function(done) {
        //uncomment below and update the code to test getUserById_0
        //instance.getUserById_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserReviewForProduct', function() {
      it('should call getUserReviewForProduct successfully', function(done) {
        //uncomment below and update the code to test getUserReviewForProduct
        //instance.getUserReviewForProduct(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserReviewForProduct_0', function() {
      it('should call getUserReviewForProduct_0 successfully', function(done) {
        //uncomment below and update the code to test getUserReviewForProduct_0
        //instance.getUserReviewForProduct_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserTradeStatistics', function() {
      it('should call getUserTradeStatistics successfully', function(done) {
        //uncomment below and update the code to test getUserTradeStatistics
        //instance.getUserTradeStatistics(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserTradeStatistics_0', function() {
      it('should call getUserTradeStatistics_0 successfully', function(done) {
        //uncomment below and update the code to test getUserTradeStatistics_0
        //instance.getUserTradeStatistics_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserVOById', function() {
      it('should call getUserVOById successfully', function(done) {
        //uncomment below and update the code to test getUserVOById
        //instance.getUserVOById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserVOById_0', function() {
      it('should call getUserVOById_0 successfully', function(done) {
        //uncomment below and update the code to test getUserVOById_0
        //instance.getUserVOById_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listBuyerOrders', function() {
      it('should call listBuyerOrders successfully', function(done) {
        //uncomment below and update the code to test listBuyerOrders
        //instance.listBuyerOrders(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listBuyerOrdersByStatus', function() {
      it('should call listBuyerOrdersByStatus successfully', function(done) {
        //uncomment below and update the code to test listBuyerOrdersByStatus
        //instance.listBuyerOrdersByStatus(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listBuyerOrdersByStatus_0', function() {
      it('should call listBuyerOrdersByStatus_0 successfully', function(done) {
        //uncomment below and update the code to test listBuyerOrdersByStatus_0
        //instance.listBuyerOrdersByStatus_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listBuyerOrders_0', function() {
      it('should call listBuyerOrders_0 successfully', function(done) {
        //uncomment below and update the code to test listBuyerOrders_0
        //instance.listBuyerOrders_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listBuyerTradeRecords', function() {
      it('should call listBuyerTradeRecords successfully', function(done) {
        //uncomment below and update the code to test listBuyerTradeRecords
        //instance.listBuyerTradeRecords(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listBuyerTradeRecords_0', function() {
      it('should call listBuyerTradeRecords_0 successfully', function(done) {
        //uncomment below and update the code to test listBuyerTradeRecords_0
        //instance.listBuyerTradeRecords_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listMyProducts', function() {
      it('should call listMyProducts successfully', function(done) {
        //uncomment below and update the code to test listMyProducts
        //instance.listMyProducts(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listMyProducts_0', function() {
      it('should call listMyProducts_0 successfully', function(done) {
        //uncomment below and update the code to test listMyProducts_0
        //instance.listMyProducts_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listMyReviews', function() {
      it('should call listMyReviews successfully', function(done) {
        //uncomment below and update the code to test listMyReviews
        //instance.listMyReviews(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listMyReviews_0', function() {
      it('should call listMyReviews_0 successfully', function(done) {
        //uncomment below and update the code to test listMyReviews_0
        //instance.listMyReviews_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listProductByPage', function() {
      it('should call listProductByPage successfully', function(done) {
        //uncomment below and update the code to test listProductByPage
        //instance.listProductByPage(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listProductByPage_0', function() {
      it('should call listProductByPage_0 successfully', function(done) {
        //uncomment below and update the code to test listProductByPage_0
        //instance.listProductByPage_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listProductsByCategory', function() {
      it('should call listProductsByCategory successfully', function(done) {
        //uncomment below and update the code to test listProductsByCategory
        //instance.listProductsByCategory(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listProductsByCategory_0', function() {
      it('should call listProductsByCategory_0 successfully', function(done) {
        //uncomment below and update the code to test listProductsByCategory_0
        //instance.listProductsByCategory_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listReviewByPage', function() {
      it('should call listReviewByPage successfully', function(done) {
        //uncomment below and update the code to test listReviewByPage
        //instance.listReviewByPage(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listReviewByPage_0', function() {
      it('should call listReviewByPage_0 successfully', function(done) {
        //uncomment below and update the code to test listReviewByPage_0
        //instance.listReviewByPage_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listReviewsByOrderId', function() {
      it('should call listReviewsByOrderId successfully', function(done) {
        //uncomment below and update the code to test listReviewsByOrderId
        //instance.listReviewsByOrderId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listReviewsByOrderId_0', function() {
      it('should call listReviewsByOrderId_0 successfully', function(done) {
        //uncomment below and update the code to test listReviewsByOrderId_0
        //instance.listReviewsByOrderId_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listReviewsByProductId', function() {
      it('should call listReviewsByProductId successfully', function(done) {
        //uncomment below and update the code to test listReviewsByProductId
        //instance.listReviewsByProductId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listReviewsByProductId_0', function() {
      it('should call listReviewsByProductId_0 successfully', function(done) {
        //uncomment below and update the code to test listReviewsByProductId_0
        //instance.listReviewsByProductId_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listReviewsByUserId', function() {
      it('should call listReviewsByUserId successfully', function(done) {
        //uncomment below and update the code to test listReviewsByUserId
        //instance.listReviewsByUserId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listReviewsByUserId_0', function() {
      it('should call listReviewsByUserId_0 successfully', function(done) {
        //uncomment below and update the code to test listReviewsByUserId_0
        //instance.listReviewsByUserId_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listSellerOrders', function() {
      it('should call listSellerOrders successfully', function(done) {
        //uncomment below and update the code to test listSellerOrders
        //instance.listSellerOrders(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listSellerOrdersByStatus', function() {
      it('should call listSellerOrdersByStatus successfully', function(done) {
        //uncomment below and update the code to test listSellerOrdersByStatus
        //instance.listSellerOrdersByStatus(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listSellerOrdersByStatus_0', function() {
      it('should call listSellerOrdersByStatus_0 successfully', function(done) {
        //uncomment below and update the code to test listSellerOrdersByStatus_0
        //instance.listSellerOrdersByStatus_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listSellerOrders_0', function() {
      it('should call listSellerOrders_0 successfully', function(done) {
        //uncomment below and update the code to test listSellerOrders_0
        //instance.listSellerOrders_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listSellerTradeRecords', function() {
      it('should call listSellerTradeRecords successfully', function(done) {
        //uncomment below and update the code to test listSellerTradeRecords
        //instance.listSellerTradeRecords(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listSellerTradeRecords_0', function() {
      it('should call listSellerTradeRecords_0 successfully', function(done) {
        //uncomment below and update the code to test listSellerTradeRecords_0
        //instance.listSellerTradeRecords_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listUserByPage', function() {
      it('should call listUserByPage successfully', function(done) {
        //uncomment below and update the code to test listUserByPage
        //instance.listUserByPage(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listUserByPage_0', function() {
      it('should call listUserByPage_0 successfully', function(done) {
        //uncomment below and update the code to test listUserByPage_0
        //instance.listUserByPage_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listUserProducts', function() {
      it('should call listUserProducts successfully', function(done) {
        //uncomment below and update the code to test listUserProducts
        //instance.listUserProducts(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listUserProducts_0', function() {
      it('should call listUserProducts_0 successfully', function(done) {
        //uncomment below and update the code to test listUserProducts_0
        //instance.listUserProducts_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listUserVOByPage', function() {
      it('should call listUserVOByPage successfully', function(done) {
        //uncomment below and update the code to test listUserVOByPage
        //instance.listUserVOByPage(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listUserVOByPage_0', function() {
      it('should call listUserVOByPage_0 successfully', function(done) {
        //uncomment below and update the code to test listUserVOByPage_0
        //instance.listUserVOByPage_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('payOrder', function() {
      it('should call payOrder successfully', function(done) {
        //uncomment below and update the code to test payOrder
        //instance.payOrder(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('payOrder_0', function() {
      it('should call payOrder_0 successfully', function(done) {
        //uncomment below and update the code to test payOrder_0
        //instance.payOrder_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('reviewProduct', function() {
      it('should call reviewProduct successfully', function(done) {
        //uncomment below and update the code to test reviewProduct
        //instance.reviewProduct(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('reviewProduct_0', function() {
      it('should call reviewProduct_0 successfully', function(done) {
        //uncomment below and update the code to test reviewProduct_0
        //instance.reviewProduct_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('searchProducts', function() {
      it('should call searchProducts successfully', function(done) {
        //uncomment below and update the code to test searchProducts
        //instance.searchProducts(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('searchProducts_0', function() {
      it('should call searchProducts_0 successfully', function(done) {
        //uncomment below and update the code to test searchProducts_0
        //instance.searchProducts_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('simulateWechatPay', function() {
      it('should call simulateWechatPay successfully', function(done) {
        //uncomment below and update the code to test simulateWechatPay
        //instance.simulateWechatPay(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('simulateWechatPay_0', function() {
      it('should call simulateWechatPay_0 successfully', function(done) {
        //uncomment below and update the code to test simulateWechatPay_0
        //instance.simulateWechatPay_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('submitPaymentProof', function() {
      it('should call submitPaymentProof successfully', function(done) {
        //uncomment below and update the code to test submitPaymentProof
        //instance.submitPaymentProof(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('submitPaymentProof_0', function() {
      it('should call submitPaymentProof_0 successfully', function(done) {
        //uncomment below and update the code to test submitPaymentProof_0
        //instance.submitPaymentProof_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateCategory', function() {
      it('should call updateCategory successfully', function(done) {
        //uncomment below and update the code to test updateCategory
        //instance.updateCategory(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateCategory_0', function() {
      it('should call updateCategory_0 successfully', function(done) {
        //uncomment below and update the code to test updateCategory_0
        //instance.updateCategory_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateMyUser', function() {
      it('should call updateMyUser successfully', function(done) {
        //uncomment below and update the code to test updateMyUser
        //instance.updateMyUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateMyUser_0', function() {
      it('should call updateMyUser_0 successfully', function(done) {
        //uncomment below and update the code to test updateMyUser_0
        //instance.updateMyUser_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateNews', function() {
      it('should call updateNews successfully', function(done) {
        //uncomment below and update the code to test updateNews
        //instance.updateNews(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateNews_0', function() {
      it('should call updateNews_0 successfully', function(done) {
        //uncomment below and update the code to test updateNews_0
        //instance.updateNews_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateProduct', function() {
      it('should call updateProduct successfully', function(done) {
        //uncomment below and update the code to test updateProduct
        //instance.updateProduct(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateProductStatus', function() {
      it('should call updateProductStatus successfully', function(done) {
        //uncomment below and update the code to test updateProductStatus
        //instance.updateProductStatus(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateProductStatus_0', function() {
      it('should call updateProductStatus_0 successfully', function(done) {
        //uncomment below and update the code to test updateProductStatus_0
        //instance.updateProductStatus_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateProduct_0', function() {
      it('should call updateProduct_0 successfully', function(done) {
        //uncomment below and update the code to test updateProduct_0
        //instance.updateProduct_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateReview', function() {
      it('should call updateReview successfully', function(done) {
        //uncomment below and update the code to test updateReview
        //instance.updateReview(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateReview_0', function() {
      it('should call updateReview_0 successfully', function(done) {
        //uncomment below and update the code to test updateReview_0
        //instance.updateReview_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateUser', function() {
      it('should call updateUser successfully', function(done) {
        //uncomment below and update the code to test updateUser
        //instance.updateUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateUser_0', function() {
      it('should call updateUser_0 successfully', function(done) {
        //uncomment below and update the code to test updateUser_0
        //instance.updateUser_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userLogin', function() {
      it('should call userLogin successfully', function(done) {
        //uncomment below and update the code to test userLogin
        //instance.userLogin(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userLogin_0', function() {
      it('should call userLogin_0 successfully', function(done) {
        //uncomment below and update the code to test userLogin_0
        //instance.userLogin_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userLogout', function() {
      it('should call userLogout successfully', function(done) {
        //uncomment below and update the code to test userLogout
        //instance.userLogout(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userLogout_0', function() {
      it('should call userLogout_0 successfully', function(done) {
        //uncomment below and update the code to test userLogout_0
        //instance.userLogout_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userRegister', function() {
      it('should call userRegister successfully', function(done) {
        //uncomment below and update the code to test userRegister
        //instance.userRegister(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userRegister_0', function() {
      it('should call userRegister_0 successfully', function(done) {
        //uncomment below and update the code to test userRegister_0
        //instance.userRegister_0(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
